GoogleCloudPlatform/php-docs-samples

.travis.yml
bigquery/api/main.php
bigquery/api/util.php
managed_vms/drupal8/.gitignore
managed_vms/drupal8/Dockerfile
managed_vms/drupal8/README.md
managed_vms/drupal8/app.yaml
managed_vms/drupal8/nginx-app.conf
managed_vms/drupal8/php.ini
managed_vms/drupal8/tests/config/install_drupal8.yml.dist
managed_vms/drupal8/tests/run-tests.sh
storage/api/listBuckets.php

@markgoldstein @tmatsuo PTAL
See the rendered README [here](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/adds-drupal-example/managed_vms/drupal8/README.md)

adds drupal8 example

---

.travis.yml
managed_vms/wordpress/README.md
managed_vms/wordpress/composer.json
managed_vms/wordpress/composer.lock
managed_vms/wordpress/phpunit.xml.dist
managed_vms/wordpress/src/Project.php
managed_vms/wordpress/src/ReportInterface.php
managed_vms/wordpress/src/ReportTrait.php
managed_vms/wordpress/src/Utils.php
managed_vms/wordpress/src/WordPressSetup.php
managed_vms/wordpress/src/files/Dockerfile
managed_vms/wordpress/src/files/app.yaml
managed_vms/wordpress/src/files/composer.json
managed_vms/wordpress/src/files/deploy_wrapper.sh
managed_vms/wordpress/src/files/gcs-media.php
managed_vms/wordpress/src/files/nginx-app.conf
managed_vms/wordpress/src/files/php.ini
managed_vms/wordpress/src/files/wp-config.php
managed_vms/wordpress/src/files/wp.php
managed_vms/wordpress/tests/DeployTest.php
managed_vms/wordpress/tests/bootstrap.php
managed_vms/wordpress/wordpress-helper.php
scripts/install_test_deps.sh

It started to work :)
I'll add README and some tests.

Adding wordpress helper

---

README.md

Preview at: https://github.com/GoogleCloudPlatform/php-docs-samples/tree/badge

Added coverage badge

---

appengine/standard/cloudsql/createTables.php
appengine/standard/users/README.md
appengine/standard/users/app.php
appengine/standard/users/app.yaml
appengine/standard/users/composer.json
appengine/standard/users/composer.lock
appengine/standard/users/index.php
appengine/standard/users/phpunit.xml.dist
appengine/standard/users/tests/DeployTest.php
appengine/standard/users/tests/LocalTest.php
appengine/standard/users/tests/bootstrap.php

Docs live at https://cloud.google.com/appengine/docs/php/users/

Add code sample for users API.

---

appengine/standard/phpmyadmin/tests/DeployTest.php

Makes downloadPhpmyadmin static

---

.travis.yml
appengine/standard/modules/README.md
appengine/standard/modules/app.php
appengine/standard/modules/app.yaml
appengine/standard/modules/backend.php
appengine/standard/modules/backend.yaml
appengine/standard/modules/tests/DeployTest.php
appengine/standard/modules/tests/ModulesTestTrait.php
testing/E2EDeploymentTrait.php
testing/GaeApp.php
testing/LocalTestTrait.php
testing/install_test_deps.sh

Code snippets for https://cloud.google.com/appengine/docs/php/modules/

Complete modules sample.

---

.travis.yml
appengine/standard/taskqueue/README.md
appengine/standard/taskqueue/app.php
appengine/standard/taskqueue/app.yaml
appengine/standard/taskqueue/composer.json
appengine/standard/taskqueue/composer.lock
appengine/standard/taskqueue/index.php
appengine/standard/taskqueue/phpunit.xml
appengine/standard/taskqueue/tests/bootstrap.php
appengine/standard/taskqueue/tests/unit/TaskQueueTest.php
appengine/standard/taskqueue/tests/unit/mocks/PushQueue.php
appengine/standard/taskqueue/tests/unit/mocks/PushTask.php

Code snippets for:
https://cloud.google.com/appengine/docs/php/taskqueue/overview-push

Added Taskqueue sample code.

---

appengine/standard/cloudsql/app.yaml
appengine/standard/cloudsql/phpunit.xml

remove all traces of createTables.php

---

testing/run_test_suite.sh

@tmatsuo PTAL
we were missing `appengine/standard/twilio` and `appengine/standard/mail` tests

automatically phpunit in any directory containing phpunit.xml

---

appengine/standard/modules/phpunit.xml
testing/run_test_suite.sh

Yay, now the test script is cleaner!

Added the necessary envvar to phpunit.xml.

---

appengine/flexible/analytics/README.md
appengine/flexible/analytics/app.php
appengine/flexible/analytics/app.yaml
appengine/flexible/analytics/composer.json
appengine/flexible/analytics/composer.lock
appengine/flexible/analytics/index.html.twig
appengine/flexible/analytics/nginx-app.conf
appengine/flexible/analytics/phpunit.xml
appengine/flexible/analytics/tests/LocalTest.php
appengine/flexible/analytics/tests/bootstrap.php
appengine/flexible/analytics/web/index.php

For https://cloud.google.com/appengine/docs/flexible/php/integrating-with-analytics

Add an analytics sample.

---

appengine/flexible/mailgun/README.md
appengine/flexible/mailgun/app.yaml
appengine/flexible/mailgun/nginx-app.conf
appengine/flexible/mailjet/README.md
appengine/flexible/mailjet/app.yaml
appengine/flexible/mailjet/nginx-app.conf
appengine/standard/mailgun/README.md
appengine/standard/mailgun/composer.json
appengine/standard/mailgun/composer.lock
appengine/standard/mailgun/index.php
appengine/standard/mailgun/test/DeployAppEngineFlexTest.php
appengine/standard/mailgun/test/bootstrap.php
appengine/standard/mailjet/README.md
appengine/standard/mailjet/app.php
appengine/standard/mailjet/composer.json
appengine/standard/mailjet/composer.lock
appengine/standard/mailjet/index.php
appengine/standard/mailjet/test/DeployAppEngineFlexTest.php
appengine/standard/mailjet/test/bootstrap.php
testing/FileUtil.php

Created a pull request just to test on travis-ci.org.

Config files for flexible/{mailgun,mailjet}.

---

appengine/wordpress/src/WordPressSetup.php
appengine/wordpress/src/files/flexible/app.yaml
appengine/wordpress/src/files/flexible/wp-config.php
appengine/wordpress/src/files/standard/wp-config.php

Added some options for choosing Cloud SQL generation and the db region.

---

appengine/flexible/twilio/README.md
appengine/flexible/twilio/app.php
appengine/flexible/twilio/app.yaml
appengine/flexible/twilio/composer.json
appengine/flexible/twilio/composer.lock
appengine/flexible/twilio/index.php
appengine/flexible/twilio/nginx-app.conf
appengine/flexible/twilio/phpunit.xml
appengine/flexible/twilio/test/DeployAppEngineFlexTest.php
appengine/flexible/twilio/test/TwilioTest.php
appengine/flexible/twilio/test/bootstrap.php

Twilio sample for app engine flex.

Twilio sample for app engine flex.

---

bigquery/api/test/utilTest.php

Fixing bigquery test.

---

appengine/flexible/memcache/app.php

This should fix the flaky test with this app.
See also:
https://github.com/GeckoPackages/GeckoMemcacheMock/issues/5

Adds expiration to Memcached#set()

---

bigquery/api/phpunit.xml.dist
bigquery/api/src/QueryCommand.php
bigquery/api/test/QueryCommandTest.php
logging/phpunit.xml.dist
logging/src/BaseCommand.php
testing/run_test_suite.sh

Also fixed the coverage configs

Fixed BigQuery and Logging tests

---

appengine/flexible/memcache/README.md

fixes memcached route in README

---

datastore/api/src/functions/concepts.php

Fixes region tags

---

logging/src/functions/log_entry_functions.php
logging/src/functions/sink_functions.php

Will "fix" 404's for some [Logging Docs Samples](https://cloud.google.com/logging/docs/api/tasks/authorization)

Adding files for moved Logging functions

---

testing/run_test_suite.sh

to get a better glance on the travis console UI

Echo the current directory before phpunit

---

datastore/api/src/functions/concepts.php

Updated region tags for docs

---

datastore/quickstart/quickstart.php

Adds newline to output statement

---

appengine/flexible/laravel/README.md
appengine/flexible/laravel/app.yaml
appengine/flexible/laravel/composer.json
appengine/flexible/laravel/composer.lock
appengine/flexible/laravel/phpunit.xml
appengine/flexible/laravel/tests/DeployTest.php
appengine/flexible/laravel/tests/bootstrap.php

These tests won't pass until after https://github.com/GoogleCloudPlatform/php-docker/pull/136 and https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/pull/19 are live.

Adds laravel example

---

endpoints/getting-started/openapi.yaml

Add region tags to openapi.yaml

---

datastore/api/composer.lock
datastore/api/test/ConceptsTest.php

Made the datastore tests less flaky

---

speech/api/composer.json
speech/api/src/TranscribeCommand.php
speech/api/src/functions/transcribe_async.php
speech/api/test/TranscribeCommandTest.php

This reverts commit a93570d8f653c5cb8d41f88b5372375f0a74653a.

Revert "removes async_recognize, speech v1 now requires gcs uri"

---

speech/api/src/TranscribeCommand.php

fixes speech sample bug

---

storage/api/composer.json
storage/api/composer.lock
storage/api/src/IamCommand.php
storage/api/src/functions/add_bucket_iam_member.php
storage/api/src/functions/remove_bucket_iam_member.php
storage/api/src/functions/view_bucket_iam_members.php
storage/api/storage.php
storage/api/test/IamCommandTest.php

Draft of Storage Bucket Level IAM samples

---

language/api/composer.json
language/api/composer.lock
language/api/src/AllCommand.php
language/api/src/EntitiesCommand.php
language/api/src/SentimentCommand.php
language/api/src/SyntaxCommand.php
language/api/src/functions/annotation_to_string.php
language/api/test/AllCommandTest.php
language/api/test/EntitiesCommandTest.php
language/api/test/SyntaxCommandTest.php

According to an earlier discussion, we still want to show users a list of all
the features that will be returned by the server.  So, I added a sample
invocation to the help documentation that serves that purpose.

Update language samples to dump all data returned from server.

---

spanner/spanner.php
spanner/src/query_data_with_index.php
spanner/src/query_data_with_new_column.php
spanner/src/read_data_with_storing_index.php
spanner/test/spannerTest.php

Essentially reorders everything to match the way commands execute in the getting started tutorial (see https://cloud.google.com/spanner/docs/getting-started/nodejs/) and adds a few minor tweakz,

addresses review changes and orders commands correctly

---

.gitignore
video/composer.json
video/quickstart.php
video/test/QuickStartTest.php

Also, add .vscode/ to the .gitignore because I'm using Visual Studio Code to edit the php source files.

Add a video quickstart and test.

---

pubsub/api/src/ProjectIdTrait.php

Proper namespace for Exception thrown in ProjectIdTrait

---

bigquery/api/src/ProjectIdTrait.php

proper namespace for exception in ProjectIdTrait (bigquery)

---

storage/api/composer.lock
storage/api/src/functions/remove_bucket_iam_member.php

adds IAM policy remover to storage samples

---

bigquery/api/src/ProjectsCommand.php
bigquery/api/src/functions/list_projects.php
bigquery/api/test/ProjectsCommandTest.php

This will fix the failing bigquery tests

add bigquery max results

---

.travis.yml
logging/api/test/ListEntriesCommandTest.php
monitoring/test/monitoringTest.php
vision/phpunit.xml.dist
vision/src/detect_web.php
vision/src/detect_web_gcs.php
vision/test/visionTest.php

see https://github.com/grpc/grpc/issues/12109

set grpc 1.4.1 in travis

---

appengine/flexible/mailjet/app.php
appengine/flexible/mailjet/composer.json
appengine/standard/mailjet/app.php
appengine/standard/mailjet/composer.json

This reverts commit d2911c693cde332626ab58c3c95bb87c79967744 (#432) as `LocalTest` is failing on travis with `400 Bad Request`.

Revert "updating Mailjet code samples for Send API v3.1 (#432)"

---

appengine/wordpress/README.md

Improvements to Wordpress on App Engine Standard README instructions based on my CUJ findings.

First commit

---

appengine/wordpress/README.md
storage/api/README.md
storage/api/composer.json
storage/api/composer.lock
storage/api/src/RequesterPaysCommand.php
storage/api/src/functions/disable_requester_pays.php
storage/api/src/functions/download_file_requester_pays.php
storage/api/src/functions/enable_requester_pays.php
storage/api/src/functions/get_requester_pays_status.php
storage/api/storage.php
storage/api/test/EncryptionCommandTest.php
storage/api/test/RequesterPaysCommandTest.php

Code samples + tests are complete and ready for review.
HOWEVER, we should not merge this until a bug in the client library is resolved (https://github.com/GoogleCloudPlatform/google-cloud-php/issues/667). The bug prevents the download function from working properly when using different accounts for the Storage owner and the requester.

Storage requester pays sample code + tests

---

storage/api/composer.json
storage/api/composer.lock
storage/api/src/functions/download_file_requester_pays.php

Per Frank's request, updated the storage library version as well as changed a variable name in the download_file_requester_pays function because of the library update.

Updated storage library version and variable name

---

appengine/standard/cloudsql/app.yaml

See https://github.com/GoogleCloudPlatform/php-docs-samples/issues/474

Fixes app.yaml comments for cloudsql example

---

video/composer.json
video/composer.lock
video/phpunit.xml.dist
video/quickstart.php
video/src/analyze_explicit_content.php
video/src/analyze_labels.php
video/src/analyze_labels_file.php
video/src/analyze_shots.php
video/test/quickstartTest.php
video/test/videoTest.php
video/video.php

Updated samples from v1beta1 to v1. Ready for review.
Major updates:
annotateVideo parameters changed
Timing syntax changed
Safe Search is now Explicit Content
Added confidence to label samples
Added category to label samples
Added shot level label detection

Updating video samples for v1

---

appengine/wordpress/README.md
appengine/wordpress/src/files/standard/composer.json

Added google/appengine-php-sdk dep and updated the README

---

endpoints/getting-started/deployment.yaml

Change SERVICE_VERSION to SERVICE_CONFIG_ID to be consistent with the Getting Started with Endpoints on Kubernetes Engine tutorial and the deployment.yaml file in the java-docs-samples, python-docs-samples, and golang samples.

Change placeholder value

---

appengine/wordpress/README.md

Add some explanations for the Cloud SQL machine types.

---

compute/helloworld/README.md

Additional minor fixes:
* used Markdown formatting to put links behind text for readability
* used code formatting for placeholder variable names
* fixed heading for consistency
* removed trailing whitespace

Fix link to google-api-php-client repo [skip ci]

---

datastore/api/test/ConceptsTest.php
testing/run_test_suite.sh

then create a summary report at the end.
fixes #534

Run through all the tests even if there's a failure

---

.travis.yml
testing/run_all_tests.sh

only run cron dependency check on 5.6

---

vision/src/detect_text_gcs.php

fix region tag

---

firestore/README.md
firestore/composer.json
firestore/firestore.php
firestore/src/list_subcollections.php
firestore/test/firestoreTest.php

Firestore List subcollections sample + tests

---

spanner/composer.json
spanner/composer.lock
spanner/spanner.php
spanner/src/add_timestamp_column.php
spanner/src/create_table_with_timestamp_column.php
spanner/src/insert_data_with_timestamp_column.php
spanner/src/query_data_with_timestamp_column.php
spanner/src/update_data_with_timestamp_column.php
spanner/test/spannerTest.php

Spanner Commit Timestamp samples

---

bigquerydatatransfer/quickstart.php
bigquerydatatransfer/test/quickstartTest.php

Follow-up to https://github.com/GoogleCloudPlatform/php-docs-samples/pull/594#pullrequestreview-111801409

BQ-DTS: test for actual API output

---

storage/src/list_objects.php
storage/src/list_objects_with_prefix.php

Update comments for list object and list object with prefix samples.

[Storage] Fix comment in PHP list objects samples

---

datastore/api/src/functions/concepts.php
datastore/tutorial/src/functions.php

[DO NOT MERGE] Updating all the region tags to have a prefix of datastore

Updating all the region tags to have a prefix of datastore

---

pubsub/api/src/functions/create_push_subscription.php
pubsub/api/src/functions/create_subscription.php
pubsub/api/src/functions/create_topic.php
pubsub/api/src/functions/delete_subscription.php
pubsub/api/src/functions/delete_topic.php
pubsub/api/src/functions/get_subscription_policy.php
pubsub/api/src/functions/get_topic_policy.php
pubsub/api/src/functions/list_subscriptions.php
pubsub/api/src/functions/list_topics.php
pubsub/api/src/functions/publish_message.php
pubsub/api/src/functions/pull_messages.php
pubsub/api/src/functions/set_subscription_policy.php
pubsub/api/src/functions/set_topic_policy.php
pubsub/api/src/functions/test_subscription_permissions.php
pubsub/api/src/functions/test_topic_permissions.php
pubsub/quickstart/quickstart.php

Need to wait for other languages and docs changes to be ready before merging

PubSub: Updates to standard region tags

---

appengine/php72/auth/test/DeployTest.php
appengine/php72/errorreporting/test/DeployTest.php
appengine/php72/helloworld/README.md
appengine/php72/trace/.gcloudignore
appengine/php72/trace/README.md
appengine/php72/trace/app.yaml
appengine/php72/trace/composer.json
appengine/php72/trace/composer.lock
appengine/php72/trace/index.php
appengine/php72/trace/php.ini
appengine/php72/trace/phpunit.xml.dist
appengine/php72/trace/test/DeployTest.php

(and also cleans up a few other samples)

Adds Trace sample

---

storage/src/enable_default_kms_key.php
storage/src/upload_with_kms_key.php

Fix region tags for storage + kms samples

[Storage] Fix region tags

---

vision/src/detect_face.php
vision/src/detect_web_with_geo_metadata.php
vision/src/detect_web_with_geo_metadata_gcs.php

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Vision region tag update

---

video/quickstart.php
video/src/analyze_labels.php

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Video Intelligence region tag update

---

language/src/analyze_entities.php
language/src/analyze_entities_from_file.php
language/src/analyze_entity_sentiment.php
language/src/analyze_entity_sentiment_from_file.php
language/src/analyze_sentiment.php
language/src/analyze_sentiment_from_file.php
language/src/analyze_syntax.php
language/src/analyze_syntax_from_file.php
language/src/classify_text.php
language/src/classify_text_from_file.php

Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.

Natural Language region tag update

---

appengine/php72/README.md
appengine/php72/auth/README.md
appengine/php72/cloudsql/README.md
appengine/php72/errorreporting/README.md
appengine/php72/errorreporting/index.php
appengine/php72/front-controller/README.md
appengine/php72/getting-started/README.md
appengine/php72/helloworld/README.md
appengine/php72/laravel-framework/README.md
appengine/php72/laravel-framework/test/DeployDatabaseTest.php
appengine/php72/slim-framework/README.md
appengine/php72/storage/README.md
appengine/php72/trace/README.md
appengine/php72/wordpress/README.md

Updates for BETA

---

language/src/analyze_entities_from_file.php
language/src/analyze_entity_sentiment_from_file.php
language/src/analyze_sentiment_from_file.php
language/src/analyze_syntax_from_file.php
language/src/classify_text_from_file.php

Updates region tags from _file_gcs to _gcs

NL region tag update

---

appengine/flexible/analytics/app.php
appengine/flexible/analytics/app.yaml
appengine/flexible/cloudsql-mysql/app.php
appengine/flexible/cloudsql-mysql/app.yaml
appengine/flexible/cloudsql-postgres/app.php
appengine/flexible/cloudsql-postgres/app.yaml
appengine/flexible/datastore/app.php
appengine/flexible/logging/app.php
appengine/flexible/mailgun/app.php
appengine/flexible/mailjet/app.php
appengine/flexible/memcache/app.php
appengine/flexible/memcache/app.yaml
appengine/flexible/sendgrid/app.php
appengine/flexible/sendgrid/app.yaml
appengine/flexible/storage/app.php
appengine/flexible/storage/app.yaml
appengine/flexible/twilio/app.php
appengine/flexible/twilio/app.yaml
pubsub/app/app.php
pubsub/app/index.php

Updating and removing region tags only

update region tags

---

appengine/php72/README.md
appengine/php72/logging/.gcloudignore
appengine/php72/logging/README.md
appengine/php72/logging/app.yaml
appengine/php72/logging/composer.json
appengine/php72/logging/composer.lock
appengine/php72/logging/index.php
appengine/php72/logging/phpunit.xml.dist
appengine/php72/logging/test/DeployTest.php

Oh, what the heck, why not a logging sample?

Adds php72 logging sample

---

vision/README.md
vision/src/detect_object.php
vision/src/detect_object_gcs.php

use same region tag as others

---

appengine/php72/laravel-framework/README.md

This configuration works up to 5.7 as of today

update comments for laravel dbsessions

---

.kokoro/docker/Makefile
.kokoro/docker/php55/Dockerfile
.kokoro/docker/php73/Dockerfile

Add php55 and php73 docker images for tests

---

language/composer.json
language/language.php
language/src/analyze_entities.php
language/src/analyze_entities_from_file.php
language/test/languageTest.php

Migrate analyze entities and analyze entities to read from GCS
Modify test cases to read single URI

[entities] Migrate to new client LanguageServiceClient in 0.16.2

---

language/composer.json
language/language.php
language/src/analyze_sentiment.php
language/src/analyze_sentiment_from_file.php

Migrate client and tests to new Client version

[sentiment] Migrate to new client LanguageServiceClient in 0.16.2

---

kms/src/remove_member_from_cryptokey_policy.php

The tag should be remove_member_from_cryptokey_policy.

Fixes region tag.

---

appengine/php72/laravel-framework/README.md
appengine/php72/laravel-framework/composer.json
appengine/php72/laravel-framework/test/DeployTest.php
appengine/php72/symfony-framework/README.md
appengine/php72/symfony-framework/composer.json
appengine/php72/symfony-framework/config/packages/prod/monolog.yaml
appengine/php72/symfony-framework/phpunit.xml.dist
appengine/php72/symfony-framework/src/Controller/LoggingController.php
appengine/php72/symfony-framework/src/EventSubscriber/ExceptionSubscriber.php
appengine/php72/symfony-framework/test/DeployDoctrineTest.php
appengine/php72/symfony-framework/test/DeploySymfonyTrait.php
appengine/php72/symfony-framework/test/DeployTest.php
appengine/php72/symfony-framework/test/bootstrap.php

Add stackdriver to symfony

---

datastore/api/src/functions/concepts.php

* `datastore_transactional_single_entity_group_read_only`

docs(samples): Update Datastore snippet for read only transaction

---

video/README.md
video/composer.json
video/src/analyze_object_tracking.php
video/src/analyze_object_tracking_file.php
video/test/videoTest.php
video/video.php

Add Video Tracking support via local file and GCS URI

Add Object Tracking support for Video

---

appengine/flexible/logging/composer.json
appengine/flexible/wordpress/composer.json
appengine/flexible/wordpress/wordpress.php
appengine/php55/grpc/composer.json
appengine/php55/wordpress/composer.json
appengine/php55/wordpress/wordpress.php
appengine/php72/errorreporting/composer.json
appengine/php72/grpc/composer.json
appengine/php72/tasks/snippets/composer.json
asset/composer.json
bigquerydatatransfer/composer.json
bigtable/composer.json
debugger/composer.json
dlp/composer.json
endpoints/getting-started/composer.json
error_reporting/composer.json
firestore/composer.json
iot/composer.json
kms/composer.json
monitoring/composer.json
pubsub/quickstart/composer.json
tasks/composer.json
texttospeech/composer.json
trace/composer.json
vision/composer.json

Supersedes https://github.com/GoogleCloudPlatform/php-docs-samples/pull/874

Dependency updates with fixes

---

storage/composer.json
storage/src/get_object_v2_signed_url.php
storage/storage.php
storage/test/ObjectSignedUrlTest.php

first line of PHP since many, many years.. Feedback appreciated :)

Storage: v2 signed url sample

---

vision/src/detect_pdf_gcs.php

Fixes preg_match in vision pdf example

---

iap/composer.json
iap/src/validate_jwt.php
iap/test/iapTest.php

fixes IAP validation

---

vision/src/detect_pdf_gcs.php

Help users determine what the output needs to be.

Update comment for param

---

bigquery/api/README.md
bigtable/README.md
datastore/api/README.md
debugger/README.md
dialogflow/README.md
dlp/README.md
error_reporting/README.md
firestore/README.md
jobs/README.md
kms/README.md
language/README.md
logging/README.md
monitoring/README.md
pubsub/api/README.md
spanner/README.md
speech/README.md
storage/README.md
tasks/README.md
texttospeech/README.md
trace/README.md
translate/README.md
video/README.md
vision/README.md

updates all product READMEs with links to the PHP sample docs

---

spanner/README.md

Add creating/deleting instructions to Spanner README

---

appengine/php72/storage/README.md

Updates app engine storage README

---

storage/composer.json
storage/src/bucket_metadata.php
storage/storage.php
storage/test/storageTest.php

[Storage] Add bucket_metadata sample

---

vision/README.md
vision/composer.json
vision/product_search.php
vision/src/product_purge_orphan_products.php
vision/src/product_purge_products_in_product_set.php
vision/test/productSearchTest.php

Add PurgeOrphan and PurgeProductsInProductSet features in PHP
Update README file with commands
Add test cases.

PurgeOrphan and PurgeProductsInProductSet

---

appengine/php72/symfony-framework/README.md
kms/README.md

remove more mention of pantheon

---

dialogflow/composer.json
dialogflow/dialogflow.php
dialogflow/src/context_create.php
dialogflow/src/context_delete.php
dialogflow/src/detect_intent_texts.php
dialogflow/src/entity_delete.php
dialogflow/src/entity_list.php
dialogflow/src/entity_type_create.php
dialogflow/src/entity_type_delete.php
dialogflow/src/intent_delete.php
dialogflow/src/session_entity_type_create.php
dialogflow/src/session_entity_type_delete.php

Fix autoloading issue for dialogflow and removes whitespace

---

storage/composer.json
storage/src/upload_object_v4_signed_url.php
storage/storage.php

No logic changes to code just renaming.

[Storage] Rename filename of sample and function

---

pubsub/api/composer.json
pubsub/api/pubsub.php
pubsub/api/src/publish_message_batch.php
pubsub/api/test/pubsubTest.php

Closes #978.
cc @hongalex
This is my first time working with the samples, so please forgive any nonsense contained below.

feat: add pubsub batch publishing sample

---

bigtable/phpunit.xml.dist
bigtable/test/BigtableTestTrait.php
bigtable/test/filterTest.php
bigtable/test/readTest.php
testing/composer.json

If this doesn't work, we will need to remove the test

retries bigtable flakey test

---

error_reporting/quickstart.php

This PR does not changing functionality, just fixes comment used in this page:
https://cloud.google.com/error-reporting/docs/reference/libraries
Individual CLA already signed.

Typo: PSR with Logging interface is PSR-3

---

appengine/php72/symfony-framework/README.md

Resolves committer issues in #1022

Add documentation for sending emails with Symfony on GAE

---

storage/composer.json
storage/src/add_bucket_conditional_iam_binding.php
storage/src/add_bucket_iam_member.php
storage/src/remove_bucket_iam_member.php
storage/src/view_bucket_iam_members.php
storage/storage.php
storage/test/IamCommandTest.php

(@frankyn) PHP Library released and this PR is now unblocked.

samples(storage): IAM conditions samples

---

appengine/php72/symfony-framework/src/EventSubscriber/ExceptionSubscriber.php
appengine/php72/symfony-framework/test/DeployDoctrineTest.php
appengine/php72/symfony-framework/test/DeploySymfonyTrait.php
appengine/php72/symfony-framework/test/DeployTest.php

Updates symfony and tests for symfony-demo 1.5

---

secretmanager/composer.json
secretmanager/quickstart.php
secretmanager/src/access_secret_version.php
secretmanager/src/add_secret_version.php
secretmanager/src/create_secret.php
secretmanager/src/delete_secret.php
secretmanager/src/destroy_secret_version.php
secretmanager/src/disable_secret_version.php
secretmanager/src/enable_secret_version.php
secretmanager/src/get_secret.php
secretmanager/src/get_secret_version.php
secretmanager/src/iam_grant_access.php
secretmanager/src/iam_revoke_access.php
secretmanager/src/list_secret_versions.php
secretmanager/src/list_secrets.php
secretmanager/src/update_secret.php
secretmanager/test/quickstartTest.php
secretmanager/test/secretmanagerTest.php

Client library bumped: https://packagist.org/packages/google/cloud-secret-manager

SecretManager bump version v1beta1->v1

---

storage/composer.json
storage/src/generate_v4_post_policy.php
storage/storage.php
storage/test/GenerateV4PostPolicy.php
storage/test/ObjectSignedUrlTest.php

Requires https://github.com/googleapis/google-cloud-php/pull/2750 to land.

storage: add v4 post policy

---

.github/renovate.json
trace/composer.json

fixes cloud trace and updates renovate

---

spanner/composer.json
spanner/src/list_backup_operations.php
spanner/src/list_database_operations.php
spanner/test/spannerBackupTest.php

Covers issue [#1050](https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1050).

fix(spanner): display LRO progress

---

cloud_sql/mysql/pdo/src/app.php
cloud_sql/sqlserver/pdo/src/app.php

Adding timeout region tags to MySQL and SQL Server samples, as discussed in PR #1099

Update Cloud SQL region tags

---

cdn/signUrl.php

fix: proper strict arguments for cdn samples

---

firestore/src/update_doc_increment.php

Should be increment here, reference for method: https://googleapis.github.io/google-cloud-php/#/docs/cloud-firestore/v1.14.0/firestore/fieldvalue?method=increment

Typo in snippet, incremet -> increment

---

bigtable/src/filter_snippets.php
bigtable/src/read_snippets.php

Changing imports and prints to be in one tag to match the other languages, sorry for the second PR

Bigtable region tags

---

pubsub/api/composer.json
pubsub/api/pubsub.php
pubsub/api/src/detach_subscription.php
pubsub/api/test/pubsubTest.php

feat: add subscription detach sample

---

dlp/composer.json
dlp/quickstart.php
dlp/src/create_inspect_template.php
dlp/src/create_trigger.php
dlp/src/deidentify_dates.php
dlp/src/deidentify_fpe.php
dlp/src/deidentify_mask.php
dlp/src/inspect_image_file.php
dlp/src/inspect_string.php
dlp/src/inspect_text_file.php
dlp/src/redact_image.php

fix: update dlp to 0.27

---

appengine/php72/getting-started/composer.json
appengine/php72/getting-started/src/app.php
appengine/php72/getting-started/src/controllers.php
appengine/php72/getting-started/test/CloudSqlTest.php
appengine/php72/getting-started/test/ControllersTest.php
appengine/php72/slim-framework/composer.json

Supersedes #1075 and #1076
cc @jdpedrie

updates for slim v4

---

cloud_sql/sqlserver/pdo/src/app.php

Fixing a commented out region tag.

fix(cloud-sql): fix region tag

---

storage/src/object_metadata.php

Adding a new metadata field to print out.

feat: add custom time to object metadata

---

functions/http_form_data/test/DeployTest.php
functions/http_form_data/test/SystemTest.php
functions/http_form_data/test/TestCasesTrait.php

chore(functions/form-data): use status code in tests

---

functions/log_helloworld/index.php

Ran into this while debugging; figured it was worth documenting.

chore(functions/log_helloworld): mention var_dump

---

functions/log_helloworld/index.php

Fixes #1219
(I was going to do this in #1218, but @bshaffer ninja'd me. 🙂

chore(functions/log): add more logging methods

---

eventarc/README.md
eventarc/generic/README.md
eventarc/generic/test/DeployTest.php
eventarc/generic/test/LocalTest.php

- Cleans up logging and adds comments to why we are using both `stderr` and `echo`
- Moves logging code out of server region tags
- Organizes READMEs, small tweaks
- Fixes `DeployTest` and adds `LocalTest`

fix: improves eventarc sample

---

functions/tips_phpinfo/composer.json
functions/tips_phpinfo/index.php
functions/tips_phpinfo/phpunit.xml.dist
functions/tips_phpinfo/test/DeployTest.php
functions/tips_phpinfo/test/IntegrationTest.php

feat(functions): add phpinfo sample

---

spanner/test/spannerBackupTest.php

test: unskip testListBackupOperations

---

appengine/flexible/supervisord/addition/phpunit.xml.dist
appengine/flexible/supervisord/replacement/phpunit.xml.dist

chore(testing): disable supervisord GAE deployment tests

---

appengine/standard/slim-framework/.gcloudignore
appengine/standard/slim-framework/composer.json
appengine/standard/slim-framework/index.php

chore(appengine): fix failing deployment tests

---

functions/firebase_rtdb/composer.json
functions/firebase_rtdb/index.php
functions/firebase_rtdb/phpunit.xml.dist
functions/firebase_rtdb/test/DeployTest.php
functions/firebase_rtdb/test/IntegrationTest.php

~**Do not merge** until b/173261804 is addressed.~

feat(functions): add Firebase RTDB sample

---

functions/helloworld_http/SampleUnitTest.php
functions/helloworld_pubsub/index.php
functions/tips_infinite_retries/index.php
functions/tips_retry/index.php

- have all `CloudEvent` functions return `void`
- rename `$data` to `$cloudEventData` for clarity
- a few small other things

fix: misc functions sample changes

---

CODEOWNERS
functions/firebase_analytics/composer.json
functions/firebase_analytics/index.php
functions/firebase_analytics/phpunit.xml.dist
functions/firebase_analytics/test/IntegrationTest.php

~**Do not merge** until this is tested against Firebase Analytics.~
**UPDATE:** @schandel and I confirmed that this works on Firebase Analytics.
(It's not possible to test this without having an Android application handy, so that's why I omitted the `DeployTest`.)

feat(functions): add firebase analytics sample

---

.kokoro/system_tests.sh

Revert SUB_DIRECTORY in favor of TEST_DIRECTORIES env var

---

appengine/standard/slim-framework/README.md
appengine/standard/slim-framework/phpunit.xml.dist

The application sample was already updated to 7.4, this change only
updates the existing documentation to reflect current reality.

Update PHP to 7.4 in docs and config

---

compute/cloud-client/helloworld/app.php
compute/cloud-client/helloworld/composer.json
compute/cloud-client/instances/composer.json
compute/cloud-client/instances/src/list_instances.php

chore: update compute to v0.3.0

---

appengine/wordpress/README.md

chore: fix link in readme

---

testing/composer.json

remove `symfony/browserkit` and reorder deps alphabetically

removes unused test dep

---

.php-cs-fixer.dist.php
.php_cs.dist
testing/composer.json
testing/run_cs_check.sh

Updating php-cs-fixer config file to support php-cs-fixer 3.0

chore: Updating php-cs-fixer config file to support php-cs-fixer 3.0

---

CODEOWNERS

chore: gives Spanner team owners

---

spanner/src/create_database_with_default_leader.php
spanner/src/get_database_ddl.php
spanner/src/get_instance_config.php
spanner/src/list_databases.php
spanner/src/list_instance_configs.php
spanner/src/query_information_schema_database_options.php
spanner/src/update_database_with_default_leader.php
spanner/test/spannerTest.php

This PR adds samples for Customer Managed Multi Region instance configurations.

feat(spanner): add samples for CMMR

---

cloud_sql/mysql/pdo/README.md
cloud_sql/mysql/pdo/app.flex.yaml
cloud_sql/mysql/pdo/app.standard.yaml
cloud_sql/mysql/pdo/src/DBInitializer.php
cloud_sql/postgres/pdo/README.md
cloud_sql/postgres/pdo/app.flex.yaml
cloud_sql/postgres/pdo/app.standard.yaml
cloud_sql/postgres/pdo/src/DBInitializer.php
cloud_sql/sqlserver/pdo/README.md
cloud_sql/sqlserver/pdo/src/DBInitializer.php

Rename CLOUD_SQL_CONNECTION_NAME to INSTANCE_CONNECTION_NAME

---

storagetransfer/composer.json
storagetransfer/phpunit.xml.dist
storagetransfer/src/quickstart.php
storagetransfer/test/StorageTransferTest.php

Creates the storagetransfer directory and adds a quickstart sample for storage transfer service, and a test

Add a quickstart sample for storage transfer service

---

functions/helloworld_pubsub/SampleUnitTest.php
functions/helloworld_pubsub/composer.json
functions/helloworld_pubsub/index.php

Update to the new [declarative function signature](https://github.com/GoogleCloudPlatform/functions-framework-php/pull/116)  style that was introduced in Functions Framework v1.1.0

refactor(functions): declarative function signature for helloworld_pubsub

---

bigtable/src/create_cluster.php

BigTable Samples - fixed getting the error message from LRO.

bug(bigtable): fixed getting the error message from LRO

---

compute/cloud-client/helloworld/composer.json

Updating cloud-compute library to GA version 1.0.0

fix(deps): update dependency google/cloud-compute to ^1.0.0

---

compute/README.md
compute/cloud-client/firewall/src/create_firewall_rule.php
compute/cloud-client/firewall/src/delete_firewall_rule.php
compute/cloud-client/firewall/src/list_firewall_rules.php
compute/cloud-client/firewall/src/patch_firewall_priority.php
compute/cloud-client/firewall/src/print_firewall_rule.php
compute/cloud-client/instances/README.md
compute/cloud-client/instances/src/create_instance.php
compute/cloud-client/instances/src/create_instance_with_encryption_key.php
compute/cloud-client/instances/src/delete_instance.php
compute/cloud-client/instances/src/disable_usage_export_bucket.php
compute/cloud-client/instances/src/get_usage_export_bucket.php
compute/cloud-client/instances/src/list_all_images.php
compute/cloud-client/instances/src/list_all_instances.php
compute/cloud-client/instances/src/list_images_by_page.php
compute/cloud-client/instances/src/list_instances.php
compute/cloud-client/instances/src/reset_instance.php
compute/cloud-client/instances/src/set_usage_export_bucket.php
compute/cloud-client/instances/src/start_instance.php
compute/cloud-client/instances/src/start_instance_with_encryption_key.php
compute/cloud-client/instances/src/stop_instance.php
compute/cloud-client/instances/test/instancesTest.php

New start/stop samples for: https://cloud.google.com/compute/docs/instances/stop-start-instance

feat(compute): Samples for start stop instances documentation page

---

functions/helloworld_storage/index.php

chore(functions/helloworld_storage): clarify comments

---

storage/src/create_bucket_dual_region.php
storage/src/create_bucket_turbo_replication.php
storage/test/storageTest.php

Closes https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1617

feat(Storage): Dual-Region Sample

---

renovate.json

Attempt to fix Renovate Configuration - issue #1545

Attempt to fix Renovate Configuration - issue #1545

---

secretmanager/src/create_secret_with_user_managed_replication.php
secretmanager/test/secretmanagerTest.php

Added sample for creating Secret with UserManaged replication
Fixes b/222386112

docs(secretmanager): Added sample for creating Secret with UserManaged replication

---

storage/src/create_bucket_dual_region.php
storage/test/storageTest.php

refactor(storage): Update Dual-Region Bucket Creation Metadata

---

storage/src/print_bucket_website_configuration.php
storage/test/storageTest.php

Wrote sample `storage_print_bucket_website_configuration` and updated the unit test `testBucketWebsiteConfiguration` in  `storageTest.php` to incoporate unit testing for this sample.

feat(Storage): Added sample to print bucket website configuration

---

spanner/src/dml_batch_update_request_priority.php
spanner/test/spannerTest.php

This PR creates a sample for DML batch update request with low priority.

Dml batch update request priority

---

bigquery/api/src/add_column_load_append.php
bigquery/api/src/add_column_query_append.php
bigquery/api/test/bigqueryTest.php
bigquery/api/test/data/test_data_extra_column.csv

Wrote and tested two samples - 
* Add a column using a load job
* Add a column using a query job

feat(Bigquery): Append column samples

---

spanner/src/add_and_drop_database_role.php
spanner/src/add_drop_database_role.php
spanner/test/spannerTest.php

This PR creates a sample for Spanner database role add and drop.

feat(Spanner): Add sample for add and drop database roles for Spanner

---

spanner/src/read_write_retry.php
spanner/test/spannerTest.php

This PR create a sample for maxRetry option in runTransaction

feat(Spanner): Add read write retry sample

---

media/videostitcher/README.md
media/videostitcher/composer.json
media/videostitcher/phpunit.xml.dist
media/videostitcher/src/create_slate.php
media/videostitcher/src/delete_slate.php
media/videostitcher/src/get_slate.php
media/videostitcher/src/list_slates.php
media/videostitcher/src/update_slate.php
media/videostitcher/test/videoStitcherTest.php

**Please enable the API in the test project**
b:202972981
Part 1 of 4: Slates (see https://cloud.google.com/video-stitcher/docs/how-to/managing-slates)

samples: add Video Stitcher samples and tests

---

error_reporting/src/report_error.php
error_reporting/test/report_errorTest.php

See https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1389

chore: upgrade error_reporting samples to new format

---

bigquery/api/src/copy_table.php
bigquery/api/src/import_from_local_csv.php
bigquery/api/src/import_from_storage_csv.php
bigquery/api/src/import_from_storage_csv_autodetect.php
bigquery/api/src/import_from_storage_csv_truncate.php
bigquery/api/src/import_from_storage_json.php
bigquery/api/src/import_from_storage_json_autodetect.php
bigquery/api/src/import_from_storage_json_truncate.php
bigquery/api/src/import_from_storage_orc.php
bigquery/api/src/import_from_storage_orc_truncate.php
bigquery/api/src/import_from_storage_parquet.php
bigquery/api/src/import_from_storage_parquet_truncate.php
bigquery/api/src/run_query_as_job.php

Fixes: https://github.com/GoogleCloudPlatform/php-docs-samples/issues/590

fix(Bigquery): remove redundant ExponentialBackoff

---

.github/workflows/lint.yml
testing/run_test_suite.sh

Final changes for moving the default branch to `main`:
- workflows
- test script
See https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1667

chore: last changes to main

---

media/videostitcher/src/create_vod_session.php
media/videostitcher/src/get_vod_ad_tag_detail.php
media/videostitcher/src/get_vod_session.php
media/videostitcher/src/get_vod_stitch_detail.php
media/videostitcher/src/list_vod_ad_tag_details.php
media/videostitcher/src/list_vod_stitch_details.php
media/videostitcher/test/videoStitcherTest.php

b:202972981
Part 3 of 4: VOD sessions (see https://cloud.google.com/video-stitcher/docs/how-to/creating-vod-sessions and https://cloud.google.com/video-stitcher/docs/how-to/inspecting-vod-sessions)

feat: add Video Stitcher samples and tests

---

appengine/flexible/logging/app.php

These region tags were removed in cl/492345188; see related PR below that added product-prefixed region tags instead.

chore(logging): remove obsolete region tags

---

media/livestream/README.md
media/livestream/composer.json
media/livestream/phpunit.xml.dist
media/livestream/src/create_input.php
media/livestream/src/delete_input.php
media/livestream/src/get_input.php
media/livestream/src/list_inputs.php
media/livestream/src/update_input.php
media/livestream/test/livestreamTest.php

b:241866780
Part 1 of 3: Inputs (see https://cloud.google.com/livestream/docs/how-to/create-input-endpoints)

feat: [LiveStream] add samples and tests

---

media/livestream/src/create_channel.php
media/livestream/src/create_channel_with_backup_input.php
media/livestream/src/delete_channel.php
media/livestream/src/get_channel.php
media/livestream/src/list_channels.php
media/livestream/src/start_channel.php
media/livestream/src/stop_channel.php
media/livestream/src/update_channel.php
media/livestream/test/livestreamTest.php

b:241866780
Part 2 of 3: Channels (see https://cloud.google.com/livestream/docs/how-to/create-channels)

feat: [LiveStream] add Channel samples and tests

---

run/helloworld/index.php

make sure <?php directive gets included in extracted docs page

fix extracted docs page for Cloud Run

---

analyticsdata/src/run_report_with_dimension_and_metric_filters.php
analyticsdata/src/run_report_with_dimension_exclude_filter.php
analyticsdata/src/run_report_with_dimension_filter.php
analyticsdata/src/run_report_with_dimension_in_list_filter.php
analyticsdata/src/run_report_with_multiple_dimension_filters.php

fixes https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1772

fix: filter names in AnalyticsData::runReport

---

cdn/signUrl.php

Description: Old region tags are replaced with product specific region tags. Please check b/272509882 for more details.
New Region tags were added using Pull Request: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1784/files

chore: cleanup un-wanted region tags

---

CODEOWNERS

chore: add DLP team to CODEOWNERS

---

dlp/src/inspect_phone_number.php
dlp/test/dlpTest.php

Added sample for **inspect data for phone numbers**
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-phone-number

Added sample for DLP : inspect data for phone numbers

---

dlp/src/inspect_custom_regex.php
dlp/test/dlpTest.php

Added sample for **Inspect data with a custom regex**
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-custom-regex

Added sample for DLP : Inspect data with a custom regex

---

media/transcoder/src/create_job_with_static_overlay.php

Please merge on approval
b:277633721

samples: remove restriction of JPEGs only for overlay images

---

pubsub/api/src/publish_avro_records.php
pubsub/api/src/subscribe_avro_records.php
pubsub/api/test/SchemaTest.php

chore(Pubsub): Fix Avro samples (Publish and Subscribe)

---

dlp/src/inspect_string_custom_hotword.php
dlp/test/dlpTest.php

Implemented sample for Inspect a string from sensitive data by using a custom hotword
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-string-custom-hotword

Added sample for DLP : Inspect a string from sensitive data by using a custom hotword

---

analyticsdata/composer.json
analyticsdata/quickstart.php
analyticsdata/quickstart_oauth2/index.php
analyticsdata/src/client_from_json_credentials.php
analyticsdata/src/get_common_metadata.php
analyticsdata/src/get_metadata_by_property_id.php
analyticsdata/src/run_batch_report.php
analyticsdata/src/run_pivot_report.php
analyticsdata/src/run_realtime_report.php
analyticsdata/src/run_realtime_report_with_multiple_dimensions.php
analyticsdata/src/run_realtime_report_with_multiple_metrics.php
analyticsdata/src/run_report.php
analyticsdata/src/run_report_with_aggregations.php
analyticsdata/src/run_report_with_cohorts.php
analyticsdata/src/run_report_with_date_ranges.php
analyticsdata/src/run_report_with_dimension_and_metric_filters.php
analyticsdata/src/run_report_with_dimension_exclude_filter.php
analyticsdata/src/run_report_with_dimension_filter.php
analyticsdata/src/run_report_with_dimension_in_list_filter.php
analyticsdata/src/run_report_with_multiple_dimension_filters.php
analyticsdata/src/run_report_with_multiple_dimensions.php
analyticsdata/src/run_report_with_multiple_metrics.php
analyticsdata/src/run_report_with_named_date_ranges.php
analyticsdata/src/run_report_with_ordering.php
analyticsdata/src/run_report_with_pagination.php
analyticsdata/src/run_report_with_property_quota.php
analyticsdata/test/analyticsDataTest.php

See https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1865
Done using [bshaffer/google-cloud-new-surface-fixer](https://github.com/bshaffer/google-cloud-new-surface-fixer)

chore: upgrade analyticsdata samples to new GAPIC

---

media/transcoder/composer.json
media/transcoder/src/create_job_from_ad_hoc.php
media/transcoder/src/create_job_from_preset.php
media/transcoder/src/create_job_from_template.php
media/transcoder/src/create_job_template.php
media/transcoder/src/create_job_with_animated_overlay.php
media/transcoder/src/create_job_with_concatenated_inputs.php
media/transcoder/src/create_job_with_periodic_images_spritesheet.php
media/transcoder/src/create_job_with_set_number_images_spritesheet.php
media/transcoder/src/create_job_with_static_overlay.php
media/transcoder/src/delete_job.php
media/transcoder/src/delete_job_template.php
media/transcoder/src/get_job.php
media/transcoder/src/get_job_state.php
media/transcoder/src/get_job_template.php
media/transcoder/src/list_job_templates.php
media/transcoder/src/list_jobs.php

See #1865 
Done using [bshaffer/google-cloud-new-surface-fixer](https://github.com/bshaffer/google-cloud-new-surface-fixer)

chore: upgrade mediatranscoder samples to new GAPIC

---

.github/workflows/lint.yml
analyticsdata/src/get_common_metadata.php
asset/test/assetSearchTest.php
spanner/src/list_instance_config_operations.php
spanner/src/list_instance_configs.php
storage/src/generate_encryption_key.php
storage/src/list_buckets.php
testing/composer.json
testing/run_staticanalysis_check.sh

Attempts to fix the PR: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1596/
So, that it can be merged.

chore: fixing static analysis tests

---

.github/workflows/lint.yml
dlp/src/inspect_text_file.php
dlp/src/k_anonymity.php

Below region tags are corrected:
- dlp_k_anonymity
- dlp_inspect_file

fix(dlp):Corrected the region tags

---

run/multi-container/hello-php-nginx-sample/service.yaml

Related to: https://github.com/GoogleCloudPlatform/cloud-run-samples/pull/234

fix: adding startup probe in run mc sample

---

storage/src/create_bucket_with_object_retention.php
storage/src/object_metadata.php
storage/src/set_object_retention_policy.php
storage/test/storageTest.php

Fixes: https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1977

feat(Storage): Add Object retention samples

---

pubsub/api/src/create_topic_with_schema_revisions.php
pubsub/api/src/update_topic_schema.php
pubsub/api/test/SchemaTest.php

feat: Add topic schema revision samples

---

pubsub/api/src/publisher_with_compression.php
pubsub/api/test/pubsubTest.php

feat: Add publisher with compression enabled sample

---

appengine/standard/tasks/snippets/README.md
storagetransfer/README.md
tasks/README.md

Adding a missing README for storage transfer samples

chore: add readme for storagetransfer

---

storagecontrol/README.md
storagecontrol/src/create_folder.php
storagecontrol/src/delete_folder.php
storagecontrol/src/get_folder.php
storagecontrol/src/list_folders.php
storagecontrol/src/rename_folder.php

Fixed README links to storage control repo, rather than storage samples.

fix(storagecontrol): fix readme

---

bigtable/composer.json
bigtable/src/hello_world.php

depends on https://github.com/googleapis/google-cloud-php/pull/7317/

chore: upgrade bigtable samples to v2

---

spanner/src/create_instance_partition.php
spanner/test/spannerTest.php

Add samples for instance partitions.

feat(spanner): add samples for instance partitions

---

appengine/standard/getting-started/index.php
appengine/standard/getting-started/src/CloudSqlDataModel.php
appengine/standard/getting-started/src/app.php
appengine/standard/getting-started/src/controllers.php
appengine/standard/getting-started/test/CloudSqlTest.php
appengine/standard/getting-started/test/ControllersTest.php
appengine/standard/getting-started/test/DeployTest.php
appengine/standard/slim-framework/index.php
compute/firewall/src/print_firewall_rule.php
endpoints/getting-started/deployment.yaml
error_reporting/src/report_error.php
monitoring/quickstart.php

chore(oss): correct apache license headers

---

secretmanager/composer.json
secretmanager/src/access_regional_secret_version.php
secretmanager/src/add_regional_secret_version.php
secretmanager/src/create_regional_secret.php
secretmanager/src/create_secret_with_user_managed_replication.php
secretmanager/src/delete_regional_secret.php
secretmanager/src/destroy_regional_secret_version.php
secretmanager/src/disable_regional_secret_version.php
secretmanager/src/enable_regional_secret_version.php
secretmanager/src/get_regional_secret.php
secretmanager/src/get_regional_secret_version.php
secretmanager/src/list_regional_secret_versions.php
secretmanager/src/list_regional_secrets.php
secretmanager/src/regional_iam_grant_access.php
secretmanager/src/regional_iam_revoke_access.php
secretmanager/src/update_regional_secret.php
secretmanager/src/update_regional_secret_with_alias.php
secretmanager/test/regionalsecretmanagerTest.php

add samples of regional secrets for all methods

feat(secretmanager): add regional secrets samples

---

CODEOWNERS

Addresses b/405801293
Requires team added to repo with write permissions

chore: add cloud-samples-infra to CODEOWNERS

---

pubsub/api/src/create_unwrapped_push_subscription.php
pubsub/api/test/pubsubTest.php

https://buganizer.corp.google.com/issues/285019494

feat(PubSub): Add CreateUnwrappedPushSubscription sample

---

pubsub/api/src/subscribe_exactly_once_delivery.php
pubsub/api/test/pubsubTest.php

https://buganizer.corp.google.com/issues/361183840

fix(PubSub): Add locational endpoint to SubscribeExactlyOnceDelivery sample
