- bigquery/api/mainTest.php
- managed_vms/drupal8/tests/run-tests.sh
- managed_vms/symfony/tests/run-tests.sh
also:
- ensures drupal path is correct
- fails bigquery without project ID
> allows gcloud to fail

- app_engine/phpmyadmin/app-e2e.yaml
- app_engine/phpmyadmin/tests/DeployTest.php
Because there's no way to automate auth with appcfg.py. I need to ommit
the trailing '$' to workaround the following bug:
https://code.google.com/p/google-cloud-sdk/issues/detail?id=573
> Use gcloud instead of appcfg.py.

- managed_vms/wordpress/src/files/gcs-media.php
WordPress has a feature called `multisites` that allows you to host multiple blogs from a single WordPress installation. With adding the blog_id as a sub directory, you can have separate directory for each blog.
> Added a blog_id for gcs media upload.

- .travis.yml
- appengine/standard/cloudsql/app.php
- appengine/standard/users/tests/unit/UsersApiTest.php
- appengine/standard/users/tests/unit/mocks/User.php
- appengine/standard/users/tests/unit/mocks/UserService.php
- testing/run_test_suite.sh
- Added more tests for the Users API sample
- Fixed failing test for cloudsql on hhvm
- Retrying when installing test dependencies
- Run tests for appengine/standard/memcache
Fixes #65 and failing build on hhvm
> Test refactorings

- appengine/flexible/datastore/README.md
- appengine/flexible/datastore/app.php
- appengine/flexible/datastore/app.yaml
- appengine/flexible/datastore/composer.json
- appengine/flexible/datastore/composer.lock
- appengine/flexible/datastore/nginx-app.conf
- appengine/flexible/datastore/phpunit.xml
- appengine/flexible/datastore/tests/LocalTest.php
- appengine/flexible/datastore/tests/bootstrap.php
- appengine/flexible/datastore/web/index.php
For https://cloud.google.com/appengine/docs/flexible/php/using-cloud-datastore
> Add a datastore sample.

- appengine/flexible/cloudsql/README.md
- appengine/flexible/cloudsql/app.php
- appengine/flexible/cloudsql/app.yaml
- appengine/flexible/cloudsql/composer.json
- appengine/flexible/cloudsql/composer.lock
- appengine/flexible/cloudsql/nginx-app.conf
- appengine/flexible/cloudsql/phpunit.xml
- appengine/flexible/cloudsql/tests/LocalTest.php
- appengine/flexible/cloudsql/tests/bootstrap.php
- appengine/flexible/cloudsql/web/index.php
For https://cloud.google.com/appengine/docs/flexible/php/using-cloud-sql
> Add a cloudsql sample.

- pubsub/src/app.php
- pubsub/web/js/pubsub.js
If the first attempt at posting a message fails.
This means one fewer error that the user has to read, figure out, and fix.
> Automatically create the topic and subscription.

- bigquery/api/src/QueryCommand.php
- bigquery/api/src/functions/run_query.php
- bigquery/api/src/functions/run_query_as_job.php
- bigquery/api/test/QueryCommandTest.php
This is so that we can include PHP in the list of languages when we add veneer samples to https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql.
I fully expect that I have a style issue on every single line. The last time I used PHP, the latest version was 4.3.
> Add option to use standard SQL syntax to BigQuery sample.

- datastore/api/composer.json
- datastore/api/composer.lock
- datastore/api/index.yaml
- datastore/api/src/functions/concepts.php
- datastore/api/test/ConceptsTest.php
* Use `hasAncestor` and `keysOnly` for simplicity.
* Simplified the transaction example.
* Complete some system tests.
> Upgraded to google/cloud to 0.11.1

- .php_cs
- datastore/api/src/functions/concepts.php
- language/api/test/AllCommandTest.php
- language/api/test/SentimentCommandTest.php
The `php-cs-fixer` team has rolled this change back, so we now have to roll it back as well 👎
> Revert "updates php-cs-fixer for 2.0"

- translate/api/composer.json
- translate/api/composer.lock
- translate/api/src/DetectLanguageCommand.php
- translate/api/src/ListCodesCommand.php
- translate/api/src/ListLanguagesCommand.php
- translate/api/src/TranslateCommand.php
- translate/api/src/snippets/detect_language.php
- translate/api/src/snippets/list_codes.php
- translate/api/src/snippets/list_languages.php
- translate/api/src/snippets/translate.php
- translate/api/test/CommandTest.php
- translate/quickstart/composer.json
- translate/quickstart/composer.lock
- translate/quickstart/quickstart.php
- translate/quickstart/test/quickstartTest.php
See 
- GoogleCloudPlatform/python-docs-samples#659
- GoogleCloudPlatform/ruby-docs-samples#113
> Translate API no longer requires an API key.

- translate/api/README.md
translate.googleapis.com will stop working.
Eng team suggests forcing the user to explicitly select a project.
> Modify link used to enable the translate api

- translate/api/README.md
cd php-docs-samples/vision/api should be cd php-docs-samples/translate/api
> Fix typo in README.md

- appengine/flexible/drupal8/README.md
- appengine/flexible/drupal8/php.ini
- appengine/flexible/drupal8/test/DeployTest.php
- Removes `php.ini` as it's no longer required
- Sets gcloud directory to fix e2e bug
- Renames EnvVars to avoid conflicts with `drupal7`
- Updates `README`
> drupal8 test fixes and improvements

- appengine/wordpress/src/files/standard/cron.yaml
Change to cron.yaml file to add quotes to description to avoid deployment error.
> fixed cron.yaml file

- pubsub/api/src/functions/pull_messages.php
Currently, the PHP snippet [here](https://cloud.google.com/pubsub/docs/pull#receive) lacks a demonstration of [Subscription::acknowledge()](https://googlecloudplatform.github.io/google-cloud-php/#/docs/google-cloud/master/pubsub%2Fsubscription?method=acknowledge) so this PR adds it.
> Acknowledge received Pub/Sub messages

- .travis.yml
Errors get thrown in travis `after_success` for partial tests because the coverage files aren't there. This adds logic to ensure we've run all the tests before running coveralls.
> fix coveralls error for partial testing

- bigquery/api/src/functions/export_table.php
Updates a comment to say "export" instead of "import" on the export table function for biquery.
> Updates a comment

- appengine/flexible/mailjet/app.php
- appengine/flexible/mailjet/composer.json
- appengine/standard/mailjet/app.php
- appengine/standard/mailjet/composer.json
Mailjet Send API v3.1 is being released, so updating the code samples to match the new Send API v3.1 configuration. Reference can be found [here](https://dev.mailjet.com/beta/).
> updating Mailjet code samples for Send API v3.1

- speech/quickstart.php
- speech/src/transcribe_async.php
- speech/src/transcribe_async_gcs.php
- speech/src/transcribe_async_words.php
- speech/src/transcribe_sync.php
- speech/src/transcribe_sync_gcs.php
- speech/src/transcribe_sync_words.php
There was some confusion where folks thought the API was only transcribing the first portion of the audio, when in fact it was because they were only using the first result. I'm updating the samples to try to reduce that confusion. See b/64934785
> Speech: Print out all results.

- appengine/flexible/laravel/test/DeployDatabaseSessionTest.php
- appengine/flexible/laravel/test/DeployTest.php
- appengine/flexible/symfony/README.md
- appengine/flexible/symfony/test/DeployTest.php
See https://github.com/GoogleCloudPlatform/community/issues/248
> update flex to use post-install-cmd

- appengine/wordpress/src/WordPressSetup.php
As it is, without this fix, WordPress setup is broken as the link is not valid without the `wordpress-` bit. Updated to the latest patch because might as well. Thanks!
> Fix link to latest WordPress version

- spanner/src/read_stale_data.php
- spanner/test/spannerTest.php
At the request of the spanner team.
> Bump spanner stale read from 10 to 15 seconds.

- iap/test/iapTest.php
This is necessary for Travis tests since we are now using different projects for IAP service account and IAP-protected App Engine app.
> IAP test fix 

- appengine/wordpress/README.md
> It is no longer necessary to explicitly create a service account

- endpoints/getting-started/deployment.yaml
For better readability, use long name options for the ESP config. Doc is here: https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options
> Use long options for the ESP config

- bigquery/quickstart/composer.json
- bigquery/quickstart/composer.lock
Version 0.3.1 is the latest version of the google/cloud-bigquery package.
It includes some breaking changes, so the api samples will need to be updated separately.
> BigQuery: update quickstart to latest package versions.

- iap/composer.json
- iap/src/validate_jwt.php
Adds PHP 7.2 support to IAP samples by using a different JWT library which supports PHP 7.2
> Add PHP 7.2 support for IAP

- auth/README.md
- dlp/README.md
- error_reporting/README.md
- iap/README.md
- kms/README.md
- language/README.md
- logging/README.md
- monitoring/README.md
- spanner/README.md
- speech/README.md
- storage/README.md
- translate/README.md
- video/README.md
- vision/README.md
> adds Open In Cloudshell to all READMEs with one depth

- spanner/src/add_column.php
- spanner/src/create_database.php
- spanner/src/create_index.php
- spanner/src/create_storing_index.php
- spanner/src/insert_data.php
- spanner/src/query_data.php
- spanner/src/query_data_with_index.php
- spanner/src/query_data_with_new_column.php
- spanner/src/read_data.php
- spanner/src/read_data_with_index.php
- spanner/src/read_data_with_storing_index.php
- spanner/src/read_only_transaction.php
- spanner/src/read_stale_data.php
- spanner/src/read_write_transaction.php
- spanner/src/update_data.php
Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* ~~GoogleCloudPlatform/ruby-docs-samples#244~~ merged
* ~~GoogleCloudPlatform/python-docs-samples#1376~~ merged
* ~~GoogleCloudPlatform/java-docs-samples#1045~~ merged
* GoogleCloudPlatform/dotnet-docs-samples#454
* GoogleCloudPlatform/golang-samples#403
> Clean up Spanner region tags.

- dlp/src/inspect_bigquery.php
- dlp/src/inspect_datastore.php
- dlp/src/inspect_file.php
- dlp/src/inspect_string.php
- dlp/src/list_categories.php
- dlp/src/list_info_types.php
- dlp/src/redact_string.php
Related:
* GoogleCloudPlatform/java-docs-samples#1051
* googleapis/nodejs-dlp#26
> Clean up DLP region tags.

- endpoints/getting-started/app.yaml
- endpoints/getting-started/deployment.yaml
We introduce a new feature where we can specify in YAML that service configuration for Endpoints is going to be managed. This means that the service will pull latest deployed service configuration automatically, rather than requiring customer to specify specific version of service configuration.
New flag:
**--rollout_strategy=managed**
Previously the only way to specify a version was using the following flag:
**--version=SERVICE_CONFIG_ID**
> Change to endpoints managed rollout

- appengine/wordpress/src/WordPressSetup.php
- appengine/wordpress/src/files/flexible/wp-cli.yml
- appengine/wordpress/src/files/standard/wp-cli.yml
`wp-cli.yml` is a configuration file for the WP-CLI command.
If there is the file, we can run WP-CLI command without `--path` parameter under the `wordpress-project` directory.
And also, we can launch local development server with `wp server` command to browse `http://localhost:8080`.
The combination of `cloud_sql_proxy` and `wp server` is very nice for me.
Thanks!
> Add wp-cli.yml into the WordPress project

- datastore/api/src/functions/concepts.php
These samples/region tags aren't used on cloud.google.com, so I'm deleting them.
Related:
- GoogleCloudPlatform/python-docs-samples#1531
- googleapis/nodejs-datastore#110
- GoogleCloudPlatform/java-docs-samples#1138
- GoogleCloudPlatform/dotnet-docs-samples#569
- GoogleCloudPlatform/ruby-docs-samples#292
- GoogleCloudPlatform/golang-samples#516
> Delete unused Datastore region tags / samples. 

- kms/src/functions.php
Hi @bshaffer,
I'm removing global location mention to generalize sample for GCS CMEK documentation. The sample is used to show developers how to set an IAM policy on a KMS key, but global location aren't supported so I want to generalize that part of the sample.
PTAL, thank you!
> [KMS] Remove global location from kms example to generalize for GCS

- speech/src/streaming_recognize.php
- speech/src/transcribe_async.php
- speech/src/transcribe_async_gcs.php
- speech/src/transcribe_async_words.php
- speech/src/transcribe_sync.php
- speech/src/transcribe_sync_gcs.php
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Speech region tag update

- bigquery/api/snippets/import_from_local_csv.php
- bigquery/api/snippets/import_from_storage_csv.php
- bigquery/api/snippets/import_from_storage_json.php
- bigquery/api/test/bigqueryTest.php
- bigquery/api/test/data/test_data.sql
Tests can now be run without relying on the test runner having certain files in GCS and tables in BigQuery. The temporary dataset and tables are now generated during the test run and the GCS files are in the cloud samples bucket, which is consistent with canonical.
> Refactor BigQuery sample tests

- translate/test/quickstartTest.php
The test required an exact string match.  So as the translation API improved, the test broke.
Make the test less fragile by just confirming the Russian word for "world" appears in the output.
> Fix fragile translation test.

- appengine/php72/wordpress/README.md
I've fixed a tiny typo. Please confirm it.
> Fix a typo in appengine/php72/wordpress/README.md

- appengine/php72/wordpress/README.md
Fix the Google Storage Console link. The "www" part does not work, it's broken.
> Fix Google Storage broken link

- vision/src/detect_image_property.php
- vision/src/detect_image_property_gcs.php
Reverts GoogleCloudPlatform/php-docs-samples#752
#752 migrated from GAPIC to handwritten.
> Revert "[detect_image_property] Update to new Vision client"

- bigquery/api/src/extract_table.php
- bigquery/api/test/bigqueryTest.php
This PR fixes the extract table sample to properly set the file format. Previously, the format was being improperly set, which resulted in defaulting to 'CSV' every time. This was identified by an internal bug report. The sample now also follows the [python canonical sample](https://github.com/googleapis/google-cloud-python/blob/9908ed55bd9940852ca410a24a568c2c5c2d4f71/bigquery/docs/snippets.py#L1984) more closely, though the PHP library [cannot yet extract a public table](https://github.com/googleapis/google-cloud-php/issues/1512).
> BigQuery: Fix extract table sample

- testing/RUN_ALL_TESTS
- testing/run_test_suite.sh
It's a bit annoying when a sample modifies `.kokoro`, root, or `testing` files and then we have to wait for 3 hours for all tests to pass. This makes it so PRs *never* run the entire test suite unless the `testing/RUN_ALL_TESTS` file is modified. Otherwise they only run tests for samples in the directories of the files modified.
It's a bit of a hack but it's the best I've come up with. Thoughts?
> Adds file to run all tests in PR

- appengine/php72/wordpress/README.md
Add explanation about /cloudsql directory.
> [Docs][appengine-php72-wordpress] Add explanation about /cloudsql directory

- iot/src/create_registry.php
add the comment about default credentials/scope for adding to this sample:
https://cloud.google.com/iot/docs/how-tos/credentials/authenticating-applications#iot-core-service-accounts-php
Currently it's pointing to list_registries.php, but to keep it consistent with other samples, we will point it to create_registry.php instead and add this comment.
> add comment for clarification of authentication sample in docs

- kms/README.md
If the link spans 2 lines, the link won't render correctly.
> Fixes link to https://cloud.google.com/kms.

- kms/src/get_cryptokey_policy.php
- kms/src/get_keyring_policy.php
- kms/test/kmsTest.php
> Adds missing KMS samples

- texttospeech/README.md
- texttospeech/composer.json
- texttospeech/quickstart.php
- texttospeech/src/synthesize_text_effects_profile.php
- texttospeech/src/synthesize_text_effects_profile_file.php
- texttospeech/test/textToSpeechTest.php
- texttospeech/texttospeech.php
Synthesize Text with Audio Profiles
> Add support for Audio Profiles

- cdn/README.md
- cdn/phpunit.xml.dist
- cdn/signUrl.php
- cdn/test/signUrlTest.php
Example implementation of generating URL signature for Cloud CDN.
Based on: https://cloud.google.com/cdn/docs/using-signed-urls#creating_signed_urls
@ahmetb
> Adds example for generating Cloud CDN Signed URLs

- spanner/src/read_write_transaction.php
- spanner/src/write_data_with_dml_transaction.php
- spanner/test/spannerTest.php
The `write_data_with_dml_transaction` function moved $200,000 from Album1 to Album2. However, Album1 is initialized with a budget of $100,000. As a result, you couldn't work through the [getting started doc](https://cloud.google.com/spanner/docs/getting-started/php/) from start to finish. This function also checked whether Album1's budget exceeded a minimum, which isn't consistent with the equivalent snippets for other languages.
In addition, the `read_write_transaction` function moved $200,000, but in the opposite direction, which was somewhat confusing.
Finally, neither function confirmed that the source album's budget was at least as large as the transfer amount.
I made both functions transfer $100,000 from Album1 to Album2. I also fixed the logic errors and updated the tests as …
> Fix Cloud Spanner budget-transfer samples

- spanner/src/read_write_transaction.php
- spanner/src/write_data_with_dml_transaction.php
- spanner/test/spannerTest.php
After #895 was merged, @jsimonweb asked me to take a slightly different approach to these changes. See, for example, my PR for the Java samples: GoogleCloudPlatform/java-docs-samples#1438
This pull request updates the PHP samples to reflect the new approach.
> More changes to Cloud Spanner budget-transfer samples

- firestore/src/update_doc_increment.php
fs_update_doc_array is already in use in https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/firestore/src/update_doc_array.php
> Update Firestore increment snippet name

- secretmanager/README.md
- secretmanager/composer.json
- secretmanager/phpunit.xml.dist
- secretmanager/quickstart.php
- secretmanager/src/access_secret_version.php
- secretmanager/src/add_secret_version.php
- secretmanager/src/create_secret.php
- secretmanager/src/delete_secret.php
- secretmanager/src/destroy_secret_version.php
- secretmanager/src/disable_secret_version.php
- secretmanager/src/enable_secret_version.php
- secretmanager/src/get_secret.php
- secretmanager/src/get_secret_version.php
- secretmanager/src/list_secret_versions.php
- secretmanager/src/list_secrets.php
- secretmanager/src/update_secret.php
- secretmanager/test/quickstartTest.php
- secretmanager/test/secretmanagerTest.php
Add initial samples for Secret Manager
/cc @dwsupplee @bshaffer
> Add Secret Manager samples

- firestore/src/add_doc_data_types.php
> feat: add firestore reference data type

- spanner/src/delete_data_with_dml.php
- spanner/src/delete_data_with_partitioned_dml.php
Being consistent with [docs](https://cloud.google.com/spanner/docs/dml-syntax#delete_examples).
> fix: use DELETE FROM for consistency

- automl/src/vision_classification_predict.php
At line 48, $content has to be passed, instead of $image which is undefined.
> Fix vision_classification_predict.php

- appengine/php72/helloworld/README.md
- appengine/php72/helloworld/app.yaml
Removing the "beta" tag from PHP 7.3. Also, I'm updating the App Engine doc to call the runtime the "PHP 7" runtime, since it supports 7.2 and 7.3, and will soon launch a beta for 7.4. So I've made a slight edit here to match the language in the App Engine doc.
> PHP 7.3 runtime is no longer in beta

- dlp/README.md
- dlp/src/categorical_stats.php
- dlp/src/create_inspect_template.php
- dlp/src/create_trigger.php
- dlp/src/deidentify_dates.php
- dlp/src/deidentify_fpe.php
- dlp/src/deidentify_mask.php
- dlp/src/inspect_bigquery.php
- dlp/src/inspect_datastore.php
- dlp/src/inspect_gcs.php
- dlp/src/inspect_image_file.php
- dlp/src/inspect_string.php
- dlp/src/inspect_text_file.php
- dlp/src/k_anonymity.php
- dlp/src/k_map.php
- dlp/src/l_diversity.php
- dlp/src/list_inspect_templates.php
- dlp/src/list_jobs.php
- dlp/src/list_triggers.php
- dlp/src/numerical_stats.php
- dlp/src/redact_image.php
- dlp/src/reidentify_fpe.php
- dlp/test/data/harmful.csv
- dlp/test/dlpTest.php
Update DLP samples to include `locations/global` in the parent field, so that the job name returned by the API matches what is used internally and what is used in the pubsub message being looked for.
See internal bug b/158100365
Also added a troubleshooting note to the DLP readme.
> Migrate DLP samples to use regional syntax in parent field

- automl/src/vision_object_detection_predict.php
Fixes AutoML Vision Object Detection prediction sample so that it passes image bytes to service.
Region tags affected:
- automl_vision_classification_predict
> fix: fixes AutoML Vision Object Detection prediction

- tasks/src/create_http_task_with_token.php
- tasks/test/tasksTest.php
add php snippet and test for creating a http task with token
> Tasks create http task with token

- spanner/README.md
- spanner/composer.json
- spanner/spanner.php
- spanner/src/delete_data.php
- spanner/test/spannerTest.php
The Deleting rows in a table section gives four different delete methods. The PHP section pointed at the documentation for $database->delete(). This only demonstrated one of the methods.
This PR adds the missing sample and includes the missing delete methods.
> Improve Spanner delete_data sample coverage

- testing/run_test_suite.sh
After weeks of unsuccessfully debugging this error, the time has come to mark it as a flakey test
> test: add flex logging as a flakey tests

- spanner/test/spannerBackupTest.php
The ListBackupOperations test is failing across all the languages due to a bug in production. This PR marks that test as skipped to unblock other PRs. Once the bug is fixed, this skip can be removed.
Towards #1186
> fix(spanner): skip failing backup test

- video/src/analyze_object_tracking.php
- video/src/analyze_object_tracking_file.php
- video/src/analyze_text_detection.php
- video/src/analyze_text_detection_file.php
Uses `video_object_tracking_gcs` to standardize with other languages
> chore: updates region tag

- functions/helloworld_http/composer.json
- functions/helloworld_http/test/DeployTest.php
- functions/helloworld_http/test/SampleUnitTest.php
- functions/helloworld_http/test/SystemTest.php
- functions/helloworld_http/test/TestCasesTrait.php
- functions/helloworld_http/test/UnitTest.php
- functions/http_content_type/composer.json
- functions/http_content_type/index.php
- functions/http_content_type/phpunit.xml.dist
- functions/http_content_type/test/DeployTest.php
- functions/http_content_type/test/SystemTest.php
- functions/http_content_type/test/TestCasesTrait.php
- functions/http_content_type/test/UnitTest.php
This PR adds two additional samples.
* functions_http_content is a new function sample that demonstrates handling different content types.
* functions_http_unit_test shows how to write a unit test for a Cloud Function. The existing UnitTest is not a good fit for use as a sample, and rather than refactor it I decided to keep both as a cross-check that the unit test sample for developers and our own (more thorough) testing stay in alignment.
> feat(functions): add functions_http_unit_test and functions_http_content

- run/README.md
Fixes cd path for sample to work properly.
Fixes https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1204
> docs(run): fix run helloworld instructions

- asset/src/search_all_iam_policies.php
- asset/src/search_all_resources.php
Standardizing some region tags. Will come back through and remove the 'inner' tags once docs are updated to represent the newly merged 'outer' tags.
> docs: standardize region tagging

- spanner/src/get_commit_stats.php
- spanner/test/spannerTest.php
This PR adds a sample to show how to get commit stats for a Cloud Spanner transaction.
> feat(spanner): add sample for commit stats

- spanner/src/create_backup.php
- spanner/test/spannerBackupTest.php
Instead of using the earliest version time of the database, uses the current time (from spanner). If we used the earliest version time of the database instead we would be creating an empty backup, since the database we are backing up is not 1 hour old (default version retention period).
> samples(spanner): PITR samples backup fix

- appengine/standard/auth/app.yaml
- appengine/standard/errorreporting/app.yaml
- appengine/standard/front-controller/app.yaml
- appengine/standard/getting-started/app.yaml
- appengine/standard/grpc/app.yaml
- appengine/standard/helloworld/app.yaml
- appengine/standard/laravel-framework/app.yaml
- appengine/standard/logging/app.yaml
- appengine/standard/memorystore/app.yaml
- appengine/standard/metadata/app.yaml
- appengine/standard/slim-framework/app.yaml
- appengine/standard/storage/app.yaml
- appengine/standard/symfony-framework/app.yaml
- appengine/standard/tasks/apps/handler/app.yaml
- appengine/standard/trace/app.yaml
This may explain why #1274's tests are failing!
> chore(App Engine): switch YAMLs to PHP 7.4

- endpoints/getting-started/test/DeployTest.php
- functions/firebase_firestore/test/DeployTest.php
- functions/firebase_remote_config/test/DeployTest.php
- functions/helloworld_pubsub/test/DeployTest.php
- functions/helloworld_storage/test/DeployTest.php
- functions/imagemagick/test/DeployTest.php
- functions/tips_infinite_retries/test/DeployTest.php
- functions/tips_retry/test/DeployTest.php
This **will not pass** until [this `php-tools` PR](https://github.com/GoogleCloudPlatform/php-tools/pull/99) is merged. (It may _also_ require other dependency updates!)
Part of #1271
> chore(functions): use processFunctionLogs in helper library

- eventarc/generic/README.md
The cloud run button isn't given any context here, so it's better to just remove it or refactor the README to make it work (see #1227)
> chore: remove cloud run button from eventarc generic README

- appengine/standard/logging/test/DeployTest.php
40 minutes -> 4 minutes. 😉 
(The secret was to add a time limit filter to the logs calls!)
> chore(GAE logging): fix slow tests

- functions/helloworld_pubsub/index.php
- functions/helloworld_pubsub/test/DeployTest.php
- functions/helloworld_pubsub/test/IntegrationTest.php
- Fixes how pubsub message data is handled in the sample
- Removes `sleep` from test, since this is handled by retrying in `processFunctionsLogs`
> fix: helloworld pubsub sample

- functions/slack_slash_command/index.php
- functions/slack_slash_command/test/IntegrationTest.php
- functions/slack_slash_command/test/TestCasesTrait.php
- functions/slack_slash_command/test/UnitTest.php
- fix timestamp - it was evaluating as empty because it was set to the string `'0'`
- Wrote a unit test for debugging and figured we might as well keep it
- misc test / function cleanup
> fix: functions slack sample

- cloud_sql/mysql/pdo/app.standard.yaml
- cloud_sql/postgres/pdo/app.standard.yaml
Now that #1336 has landed (and #1242 has been obviated), I'm moving some `app.yaml` fixes from the latter to a separate PR.
> chore(Cloud SQL): upgrade PHP version from 7.2 to 7.4

- .github/.blunderbuss.yml
- CODEOWNERS
Updates the CODEOWNERs file and Blunderbuss config for new teamsync managed groups
Before merging, please make sure the follow teams have write access for this repo:
> Update CODEOWNERS / Blunderbuss for SoDA teams

- compute/cloud-client/instances/README.md
- compute/cloud-client/instances/src/disable_usage_export_bucket.php
- compute/cloud-client/instances/src/get_usage_export_bucket.php
- compute/cloud-client/instances/src/set_usage_export_bucket.php
- compute/cloud-client/instances/test/instancesTest.php
Refactoring set, get and disable usage export bucket samples by putting them in separate files. Removal of compute_instances_verify_default_value region tag as we decided not to use it.
> Refactoring set, get and disable usage export bucket samples

- spanner/src/create_client_with_query_options.php
> chore(spanner): pin stats package to latest

- compute/cloud-client/instances/composer.json
- compute/cloud-client/instances/src/create_instance.php
- compute/cloud-client/instances/src/delete_instance.php
- compute/cloud-client/instances/src/wait_for_operation.php
Refactoring compute_instances_operation_check sample to repeat the wait operation if it hasn't finished yet. This change is made per recommendation from library team (AC Tools).
What has been done:
- moved wait_for_operation to a separate file
- added while loop around library wait call
- added autoDelete flag to disks created with the instance to make sure they are cleaned up after VM deletion
> Refactoring compute_instances_operation_check sample

- storage/src/set_public_access_prevention_inherited.php
- storage/src/set_public_access_prevention_unspecified.php
- storage/test/PublicAccessPreventionTest.php
Changed the references of `unspecified` in storage samples and tests to `inherited` as per #1534 
~One test would fail right now as the API hasn't changed the response yet.~
> Storage: Changed references from 'unspecified' to 'inherited'

- testing/run_test_suite.sh
Composer 2 changed the way `composer check-platform-reqs` works (we need to generate the lock file before checking), and also I updated the script to allow for automatically skipping when sub-dependencies don't meet requirements (like the functions framework). This means adding `php` to the `required` section of `composer.json` is no longer necessary.
> fix: php version check for tests

- functions/helloworld_http/SampleUnitTest.php
- functions/helloworld_http/composer.json
- functions/helloworld_http/index.php
- functions/helloworld_pubsub/composer.json
Update to the new [declarative function signature](https://github.com/GoogleCloudPlatform/functions-framework-php/pull/116)  style that was introduced in Functions Framework v1.1.0
> refactor(functions): declarative function signature for helloworld_http

- functions/helloworld_pubsub/composer.json
- testing/check_version.php
- testing/composer.json
- testing/run_test_suite.sh
Require that PHP versions are explicitly marked in `composer.json` to be skipped. This avoids things like sub-dependencies being updated to a newer PHP version causing tests to be skipped unknowingly (see #1562)
> fix: php version check

- storage/src/set_client_endpoint.php
- storage/test/storageTest.php
1. Added a sample for `storage_set_client_endpoint` and its test.
Ran the test locally and its successful:
```
➜  storage git:(storage_set_endpoint) ✗ XDEBUG_MODE=coverage  ../testing/vendor/bin/phpunit --verbose -c phpunit.xml.dist test/storageTest.php --filter="testSetClientEndpoint"         
PHPUnit 8.5.23 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.28 with Xdebug 3.1.2
Configuration: /usr/local/google/home/vishwarajanand/github/php-docs-samples/storage/phpunit.xml.dist
.                                                                   1 / 1 (100%)
Time: 1.7 seconds, Memory: 10.00 MB
OK (1 test, 3 assertions)
Generating code coverage report in Clover XML format ... done [219 ms]
➜  storage git:(storage_set_endpoint) ✗
```
~~## Still in progress:~~
~~1. Still …
> Adding a sample to set storage endpoint

- storage/src/print_bucket_acl_for_user.php
- storage/src/print_file_acl_for_user.php
- storage/test/ObjectAclTest.php
Implement 2 samples:
```
storage_print_file_acl_for_user
storage_print_bucket_acl_for_user
```
1. Adding `print_file_acl_for_user.php` and `print_bucket_acl_for_user.php`.
2. Adding tests for the above 2 samples here: `ObjectAclTest.php`
1. Ran the samples:
```
➜  storage git:(storage_print_acl_for_user) ✗ php src/add_bucket_acl.php $GOOGLE_STORAGE_BUCKET_LEGACY 'allAuthenticatedUsers' 'READER' 
Added allAuthenticatedUsers (READER) to gs://gcp-acl_test_bucket ACL
➜  storage git:(storage_print_acl_for_user) ✗ php src/print_bucket_acl_for_user.php $GOOGLE_STORAGE_BUCKET_LEGACY 'allAuthenticatedUsers'    
allAuthenticatedUsers: READER
➜  storage git:(storage_print_acl_for_user) ✗ 
➜  storage git:(storage_print_acl_for_user) ✗ php src/add_object_acl.php $GOOGLE_STORAGE_BUCKET_LEGACY …
```
> Adding samples for printing bucket/object ACLs

- firestore/src/query_collection_group_filter_eq.php
Per https://github.com/googleapis/google-cloud-php/issues/2542, user claimed that they cannot get the `collectionGroup` query return successfully. Upon investigation, it seems we disable indexes on collection group by default: [source link to docs](https://firebase.google.com/docs/firestore/query-data/index-overview#automatic_indexing).
1. Adding a comment in the sample to ensure users have more clarity for querying collection groups.
2. Linked the source docs page about automatic indexing
1. Created a document structure within a subcollection
2. Created a single field index within a field of subcollection so that it can be queried
3. Renamed the subcollection, field and value identifiers in [this PHP sample](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/firestore/src …
> Firestore - Adding a warning to enable indexing before querying collection group

- storage/src/upload_object_stream.php
- storage/test/ObjectsTest.php
Per https://github.com/googleapis/google-cloud-php/issues/4155, our users are requesting a sample / documentation for uploading objects of a fixed chunk sizes to Storage. Existing samples cover file/memory uploads in entirety but not with controlled chunk sizes.
**NOTE:** This change will replace the samples already published [on this devsite link](https://cloud.google.com/storage/docs/samples/storage-stream-file-upload#storage_stream_file_upload-php).
1. Added a new sample: `storage_stream_file_upload`
2. Added test for `testUploadAndDownloadObjectStream`
3. Removed sample tag from older sample to upload files: `upload_object.php`
1. Uploaded a local file by executing sample:
```
➜  storage git:(upload_chunked_stream) ✗ php src/upload_object_stream.php $GOOGLE_STORAGE_BUCKET …
```
> Added new sample for storage to upload chunked stream

- appengine/flexible/storage/app.php
- appengine/standard/auth/test/DeployTest.php
- appengine/standard/grpc/test/DeployTest.php
- appengine/standard/slim-framework/index.php
- asset/src/list_assets.php
- bigtable/test/BigtableTestTrait.php
- compute/api-client/helloworld/app.php
- iot/src/list_devices_for_gateway.php
- secretmanager/quickstart.php
- spanner/src/query_data_with_nested_struct_field.php
- storage/src/delete_hmac_key.php
- testing/composer.json
- video/src/analyze_object_tracking_file.php
- addresses phpunit errors on PHP 7.3 (see https://github.com/sebastianbergmann/phpunit/issues/5016)
- Pin `php-cs-fixer` to `v3.8.0` because `v3.9` broke several things for us.
- Fix a few cs problems that the later version actually caught
> chore: revert cs-fixer and fix a few styles

- bigquery/api/phpunit.xml.dist
- bigquery/api/src/dry_run_query.php
- bigquery/api/src/query_no_cache.php
- bigquery/api/test/bigqueryTest.php
Adding samples which are missing on these pages:
`bigquery_query_dry_run` -> https://cloud.google.com/bigquery/docs/dry-run-queries
`bigquery_query_no_cache` -> https://cloud.google.com/bigquery/docs/cached-results
> Passes in my local
```
➜  api git:(bigquery_samples) XDEBUG_MODE=coverage ../../testing/vendor/bin/phpunit --verbose -c phpunit.xml.dist test/*
PHPUnit 8.5.27 #StandWithUkraine
Runtime:       PHP 7.3.33 with Xdebug 3.1.5
Configuration: /usr/local/google/home/vishwarajanand/github/php-docs-samples/bigquery/api/phpunit.xml.dist
Error:         This version of PHPUnit does not support code coverage on PHP 8
.......................                                           23 / 23 (100%)
Time: 1.73 minutes, Memory: 58.00 MB
OK (23 tests, 64 assertions)
➜  api …
```
> feat: add new samples for bigquery

- storage/composer.json
- storage/src/create_bucket_dual_region.php
- storage/test/storageTest.php
Fixing sample for dual region bucket creation
Fixes: 
https://github.com/googleapis/google-cloud-php/issues/5313
and
https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1645
```
php-docs-samples/storage % php src/create_bucket_dual_region.php 'samples-create-bucket-dual-region-xyz12321' 'US' 'US-EAST1' 'US-WEST1'
Created dual-region bucket 'samples-create-bucket-dual-region-xyz12321' in 'US-EAST1+US-WEST1'
php-docs-samples/storage %
```
Shows up as:
> feat: samples for dual region bucket creation

- firestore/src/data_reference_document.php
- firestore/src/data_reference_document_path.php
- firestore/src/setup_dataset.php
This PR is to address https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1532
The document name is correctly used in the repo since the setup code inserted a document of just `lovelace` however it seems it is preferable to match public documentations, I have modified the relevant files to reference `alovelace` instead.
> fix: change Firestore document name to match public docs

- spanner/test/spannerBackupTest.php
- testing/run_test_suite.sh
This aims to run the Backup tests only when requested. That will be recognised by the presence of a label `spanner:run-backup-tests` on the PR.
If the label isn't present, the backup tests will be skipped.
Otherwise they will be run.
This will heavily help in the frequent quota errors we are seeing in spanner related PRs.
> feat(Spanner): Run backup tests only when requested explicitly

- bigquery/api/test/bigqueryTest.php
From latest builds, [ref](https://source.cloud.google.com/results/invocations/d79d96e9-00a9-4e6b-a011-3cdebb3a7c9b/targets/cloud-devrel%2Fphp-docs-samples%2Fpresubmit%2Fphp73/log) it seems bigquery tests are breaking and hence all downstream tests.
The tests were failing because it queries grouped counts of values in `publicdata.samples.shakespeare`. Since, there's no order as of today expected fields are not showing up. There has been no change in pubic dataset, so I added an ordering to make the tests reliable.
> fix (bigquery): add order into test query

- cloud_sql/sqlserver/pdo/Dockerfile
See: https://blog.codito.dev/2022/11/composer-binary-only-docker-images/
> Use binary-only images for installing Composer

- CODEOWNERS
I know php-samples-reviewers only has 2 people, but we should update the php-sample-reviewers so that it's synced correctly. php-admin are the repo owners.
> fix:  codeowners to reflect standards

- bigquery/stackoverflow/stackoverflow.php
[Relevant cgc website](https://cloud.google.com/bigquery/docs/quickstarts/quickstart-client-libraries#complete_source_code)
[Relevant region tag](https://devrel.corp.google.com/snippets/bigquery_simple_app_all)
1. Show `<?php` tag in quickstart pages coz without this tag, the contents of the file is printed rather than getting executed. User needs to know about the tag else they cannot use the quickstart guide.
2. Exclude license and file description.
> chore(bigquery): show php tag in quickstart sample

- pubsub/api/composer.json
This change has already been done in client library, https://github.com/googleapis/google-cloud-php/pull/5685. 
Backporting to samples now.
With this change, the lint errors are fixed.
> fix: removed abandoned package from composer

- .github/workflows/lint.yml
While building an unrelated PR in this repo, I got lint errors, [link](https://github.com/GoogleCloudPlatform/php-docs-samples/actions/runs/4170853588/jobs/7220204731). Its a required workflow, so I need to fix the errors. But the lint logs are not very readable, it loops over all product folders and checks each of them.
1. Added a log statement which prints the product folder it it checking.
I do not have a workflow test repo, so I tested in local as a bash script.
> chore: make lint logs easier to read

- bigquery/stackoverflow/stackoverflow.php
- bigquery/stackoverflow/test/stackoverflowTest.php
[Relevant cgc website](https://cloud.google.com/bigquery/docs/quickstarts/quickstart-client-libraries#complete_source_code)
[Relevant region tag](https://devrel.corp.google.com/snippets/bigquery_simple_app_all)
1. Remove the use of env var `GOOGLE_CLOUD_PROJECT` or command line args for running `bigquery/stackoverflow/stackoverflow.php`.
2. Relevant changes in test.
1. Tests are passing in php74.
```
bigquery/stackoverflow % ../../testing/vendor/bin/phpunit -c phpunit.xml.dist            (git)-[chore_show_click_to_copy_code]-
PHPUnit 8.5.26 #StandWithUkraine
Error:         XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
.                                                                   1 / 1 (100%)
Time: 1.82 seconds, Memory: 8.00 MB
OK (1 test, 1 assertion) …
```
> chore(bigquery): prefer env var to arguments

- cdn/signUrl.php
Cloud CDN Snippets are missing product's specific region tags. In this PR, we are only adding region tags. No code changes. For more details, refer to [b/264905390](b/264905390).
> fix: Add missing product region tags for Cloud CDN snippets

- dlp/src/inspect_string_with_exclusion_dict.php
- dlp/test/dlpTest.php
Implemented sample for Inspect a string for sensitive data, using exclusion dictionary
Added test cases for the same 
Reference: https://cloud.google.com/dlp/docs/creating-custom-infotypes-rules#omit_specific_email_address_from_email_address_detector_scan
> Added sample for DLP :  Inspect a string for sensitive data, using exclusion dictionary

- dlp/src/deidentify_simple_word_list.php
- dlp/test/dlpTest.php
- media/livestream/composer.json
Added sample for de-identify sensitive data with a simple word list
Reference: https://cloud.google.com/dlp/docs/samples/dlp-deidentify-simple-word-list
> Added sample for DLP : de-identify sensitive data with a simple word list

- dlp/src/deidentify_exception_list.php
- dlp/test/dlpTest.php
Added sample for create an exception list for de-identification
Reference: https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#exception_list
> Added sample for DLP : create an exception list for de-identification

- dlp/src/inspect_string_custom_omit_overlap.php
- dlp/test/dlpTest.php
Added sample for DLP: Inspect a string for sensitive data, omitting custom matches.
Added test cases for the same.
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-string-custom-omit-overlap#dlp_inspect_string_custom_omit_overlap-java
> Added sample for DLP: Inspect a string for sensitive data, omitting custom matches

- dlp/src/inspect_string_omit_overlap.php
- dlp/test/dlpTest.php
- media/livestream/composer.json
Implemented sample for Inspect a string for sensitive data, omitting overlapping matches on person and email
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-string-omit-overlap
> Added sample for DLP : Inspect a string for sensitive data, omitting overlapping matches on person and email

- dlp/src/deidentify_redact.php
- dlp/test/dlpTest.php
Added sample for DLP: De-identify data Redacting with matched input values 
Added test cases for the same 
Reference: https://cloud.google.com/dlp/docs/deidentify-sensitive-data#redactconfig
> Added sample for DLP: De-identify data Redacting with matched input values

- dlp/src/inspect_hotword_rule.php
- dlp/test/dlpTest.php
Implemented sample for Inspect data with a hotword rule and added test cases for the same.
Reference: https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-mrn
> Added sample for DLP : Inspect data with a hotword rule

- dlp/src/inspect_string_custom_excluding_substring.php
- dlp/test/dlpTest.php
Implemented sample for Inspect a string for sensitive data, excluding a custom substring
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-string-custom-excluding-substring
> Added sample for DLP : Inspect a string for sensitive data, excluding a custom substring

- dlp/src/inspect_string_with_exclusion_regex.php
- dlp/test/dlpTest.php
Implemented sample for Inspect a string, excluding REGEX matches
Reference: https://cloud.google.com/dlp/docs/samples/dlp-inspect-string-with-exclusion-regex
> Added sample for DLP : Inspect a string, excluding REGEX matches

- pubsub/api/src/publish_with_retry_settings.php
- pubsub/api/test/pubsubTest.php
Addresses https://github.com/googleapis/google-cloud-php/issues/5616
Samples for other languages are published here [on this doc](https://cloud.google.com/pubsub/docs/publisher#retry) and are present for Java, Python, DotNet.
> feat(pubsub): publish with retrySettings

- dlp/src/deidentify_replace.php
- dlp/src/inspect_string_multiple_rules.php
- dlp/test/dlpTest.php
Implemented sample for De-identify sensitive data to replace matched input values.
Reference: https://cloud.google.com/dlp/docs/deidentify-sensitive-data.md#dlp_deidentify_replace-java
> Added sample for DLP : De-identify sensitive data to replacing matched input values.

- dlp/src/deidentify_table_bucketing.php
- dlp/src/deidentify_table_condition_infotypes.php
- dlp/src/deidentify_table_condition_masking.php
- dlp/src/deidentify_table_infotypes.php
- dlp/src/deidentify_table_row_suppress.php
- dlp/test/data/table1.csv
- dlp/test/data/table2.csv
- dlp/test/dlpTest.php
Implemented below samples 
1) [dlp_deidentify_table_infotypes](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_found_in_columns)
2) [dlp_deidentify_table_condition_masking](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_based_on_the_value_of_another_column)
3) [dlp_deidentify_table_condition_infotypes](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_only_when_specific_conditions_are_met_on_another_field)
4) [dlp_deidentify_table_bucketing](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_without_inspection)
5) [dlp_deidentify_table_row_suppress](https://cloud.google.com/dlp/docs/examples-deid-tables.md#suppress_a_row_based_on_the_content_of_a_column)
Added test cases for the …
> Added sample for DLP : De-identify Table Samples

- dlp/src/inspect_augment_infotypes.php
- dlp/src/inspect_column_values_w_custom_hotwords.php
- dlp/src/inspect_image_all_infotypes.php
- dlp/src/inspect_image_listed_infotypes.php
- dlp/src/inspect_table.php
- dlp/test/dlpTest.php
Implemented below samples
1) [dlp_inspect_image_all_infotypes](https://cloud.google.com/dlp/docs/inspecting-images.md#dlp-inspect-image-all-infotypes-java)
2) [dlp_inspect_image_listed_infotypes](https://cloud.google.com/dlp/docs/samples/dlp-inspect-image-listed-infotypes)
3) [dlp_inspect_augment_infotypes](https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#augment_a_built-in_infotype_detector)
4) [dlp_inspect_column_values_w_custom_hotwords](https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-column-values)
5) [dlp_inspect_table](https://cloud.google.com/dlp/docs/inspecting-structured-text.md#dlp-inspect-table-java)
> Added sample for DLP :  Inspect info types samples

- dlp/src/redact_image_all_infotypes.php
- dlp/src/redact_image_all_text.php
- dlp/src/redact_image_colored_infotypes.php
- dlp/src/redact_image_listed_infotypes.php
- dlp/test/dlpTest.php
Implemented below samples :
[1) dlp_redact_image_listed_infotypes](https://cloud.google.com/dlp/docs/redacting-sensitive-data-images#dlp-redact-image-listed-infotypes-java)
[2) dlp_redact_image_all_text](https://cloud.google.com/dlp/docs/redacting-sensitive-data-images#redacting_all_text_from_an_image)
[3) dlp_redact_image_all_infotypes](https://cloud.google.com/dlp/docs/redacting-sensitive-data-images#dlp-redact-image-listed-infotypes-java)
[4) dlp_redact_image_colored_infotypes](https://cloud.google.com/dlp/docs/samples/dlp-redact-image-colored-infotypes)
> Added sample for DLP : Redact data from image files

- securitycenter/src/create_notification.php
- securitycenter/src/delete_notification.php
- securitycenter/src/get_notification.php
- securitycenter/src/list_notification.php
- securitycenter/src/update_notification.php
Contains only comment updates to allow new parent types (b/263299056)
> docs(scc-samples): update comments to add new parent resource types

- bigquery/api/phpunit.xml.dist
- bigquery/stackoverflow/phpunit.xml.dist
- bigtable/phpunit.xml.dist
- datastore/api/phpunit.xml.dist
- datastore/quickstart/phpunit.xml.dist
- datastore/tutorial/phpunit.xml.dist
- firestore/phpunit.xml.dist
- pubsub/api/phpunit.xml.dist
- pubsub/app/phpunit.xml.dist
- pubsub/quickstart/phpunit.xml.dist
- spanner/phpunit.xml.dist
- storage/phpunit.xml.dist
<details>
<summary>Script ran to migrate configurations is below</summary>
```
#!/bin/bash
php_samples_path="$HOME/github/php-docs-samples/"
products=(
"testing"
"bigquery"
"bigtable"
"spanner"
"firestore"
"datastore"
"storage"
"pubsub"
)
for phpunit_config in $(find * -name 'phpunit.xml*' -not -path '*vendor/*' );
do
dir=$(dirname $phpunit_config)
if [[ "${products[@]}" != *"${dir%%/*}"* ]]; then
continue
fi
echo -e "\n RUNNING for => $phpunit_config\n"
$php_samples_path/testing/vendor/bin/phpunit  -c $phpunit_config --migrate-configuration && git add "${phpunit_config}"
done
```
</details>
[Log file](https://paste.googleplex.com/5243033002967040) showing no failure
Context: https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1863 was giving failures when the phpunit configs …
> chore: phpunit migrate configuration

- error_reporting/composer.json
- error_reporting/src/report_error.php
See https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1865
Done using [bshaffer/google-cloud-new-surface-fixer](https://github.com/bshaffer/google-cloud-new-surface-fixer)
> chore: upgrade errorreporting samples to new GAPIC

- media/videostitcher/src/create_cdn_key.php
- media/videostitcher/src/create_cdn_key_akamai.php
- media/videostitcher/src/create_live_config.php
- media/videostitcher/src/create_live_session.php
- media/videostitcher/src/create_slate.php
- media/videostitcher/src/create_vod_session.php
- media/videostitcher/src/delete_cdn_key.php
- media/videostitcher/src/delete_live_config.php
- media/videostitcher/src/delete_slate.php
- media/videostitcher/src/get_cdn_key.php
- media/videostitcher/src/get_live_ad_tag_detail.php
- media/videostitcher/src/get_live_config.php
- media/videostitcher/src/get_live_session.php
- media/videostitcher/src/get_slate.php
- media/videostitcher/src/get_vod_ad_tag_detail.php
- media/videostitcher/src/get_vod_session.php
- media/videostitcher/src/get_vod_stitch_detail.php
- media/videostitcher/src/list_cdn_keys.php
- media/videostitcher/src/list_live_ad_tag_details.php
- media/videostitcher/src/list_live_configs.php
- media/videostitcher/src/list_slates.php
- media/videostitcher/src/list_vod_ad_tag_details.php
- media/videostitcher/src/list_vod_stitch_details.php
- media/videostitcher/src/update_cdn_key.php
- media/videostitcher/src/update_cdn_key_akamai.php
- media/videostitcher/src/update_slate.php
See https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1865
Done using [bshaffer/google-cloud-new-surface-fixer](https://github.com/bshaffer/google-cloud-new-surface-fixer)
~~**NOTE**: The API broke backwards compatibility, so these tests are failing because the code needed to change significantly to get the samples to pass.~~ this has been fixed in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1876
> chore: upgrade videostitcher samples to new GAPIC

- texttospeech/composer.json
- texttospeech/quickstart.php
- texttospeech/src/list_voices.php
- texttospeech/src/synthesize_ssml.php
- texttospeech/src/synthesize_ssml_file.php
- texttospeech/src/synthesize_text.php
- texttospeech/src/synthesize_text_effects_profile.php
- texttospeech/src/synthesize_text_effects_profile_file.php
- texttospeech/src/synthesize_text_file.php
Reverts GoogleCloudPlatform/php-docs-samples#1880
As this need not to be merged until the new surface is GA.
More details at #1886
> Revert "chore: upgrade texttospeech samples to new surface"

- media/livestream/composer.json
- media/livestream/src/create_asset.php
- media/livestream/src/delete_asset.php
- media/livestream/src/get_asset.php
- media/livestream/src/get_pool.php
- media/livestream/src/list_assets.php
- media/livestream/src/update_pool.php
- media/livestream/test/livestreamTest.php
b:264616218
Please merge this PR for me once it is approved
> feat(Live Stream): add samples and tests for assets and pools

- run/multi-container/hello-php-nginx-sample/README.md
- run/multi-container/hello-php-nginx-sample/php-app/Dockerfile
- run/multi-container/hello-php-nginx-sample/php-app/cloudrun.ini
- run/multi-container/hello-php-nginx-sample/php-app/opcache.ini
- run/multi-container/hello-php-nginx-sample/service.yaml
**Updates include:**
* Adding note in readme about lack of explicit settings defining php-fpm workers
* Add `opcache.ini` content into Dockerfile
* Swap from `Mi` memory unit to `M`
> fix: updates cloud run mc php nginx sample

- logging/src/write_log.php
Update the code sample for [write a log][1] to show how to explicitly add severity.
[1]: https://cloud.google.com/logging/docs/samples/logging-write-log-entry#logging_write_log_entry-php
> fix: update write log sample to setup severity

- error_reporting/quickstart.php
- error_reporting/test/quickstartTest.php
align code sample for error reporting with code in other languages (b/275730159):
- use the same error message across samples in all languages
- use correct env var for capturing project Id in the managed environment
> fix: refactor error reporting code sample

- appengine/flexible/metadata/test/DeployTest.php
- monitoring/test/alertsTest.php
- pubsub/api/test/pubsubTest.php
- speech/test/speechTest.php
- storage/test/IamTest.php
- vision/test/visionTest.php
We are seeing warnings like below which will be fixed by this PR:
```
There was 1 warning:
1) Google\Cloud\Samples\PubSub\PubSubTest::testPublishAndSubscribeWithOrderingKeys
assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.
```
ref: https://github.com/sebastianbergmann/phpunit/issues/4086
> fix: deprecate assertRegexp usage over assertMatchesRegularExpression

- spanner/src/directed_read.php
- spanner/test/spannerTest.php
This is dependent on https://github.com/googleapis/google-cloud-php/pull/6078
Once the dependent PR merged, need to update the `composer.json` file to match the `google-cloud-php` latest version.
> feat(Spanner): Add directed read samples

- storagetransfer/phpunit.xml.dist
Removes the following warning:
```
➜  storagetransfer git:(main) ✗ ../testing/vendor/bin/phpunit -c phpunit.xml.dist --filter="does_not_exist" 
PHPUnit 9.6.18 by Sebastian Bergmann and contributors.
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
Warning:       Your XML configuration validates against a deprecated schema. <------ FIXES THIS WARNING ########
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
No tests executed!
➜  storagetransfer git:(main) ✗ ../testing/vendor/bin/phpunit -c phpunit.xml.dist --migrate-configuration   
PHPUnit 9.6.18 by Sebastian Bergmann and contributors.
Created backup:         /usr/local/google/home/vishwarajanand/github/php-docs-samples/storagetransfer/phpunit.xml.dist.bak
Migrated configuration: …
```
> chore: migrate storage transfer phpunit config

- testing/run_test_suite.sh
fixes https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1932 by checking to see if deployment tests exist in either `test` or `tests`
> chore(tests): check both "test" and "tests" dirs

- media/livestream/test/livestreamTest.php
addresses https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1886
I missed upgrading the test directory, which makes calls to the client directly, in https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1870
> chore: upgrade media-livestream tests to new surface

- storage/src/create_bucket_hierarchical_namespace.php
- storage/test/storageTest.php
Added sample for HNS:
```
➜  storage git:(main) ✗ ../testing/vendor/bin/phpunit -c phpunit.xml.dist --filter="::testCreateBucketHnsEnabled"
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
.                                                                   1 / 1 (100%)
Time: 00:11.752, Memory: 12.00 MB
OK (1 test, 3 assertions)
➜  storage git:(main) ✗ 
```
partially addresses https://github.com/googleapis/google-cloud-php/issues/7357
> feat(storage): Add samples for HNS

- storagecontrol/src/create_folder.php
- storagecontrol/src/delete_folder.php
- storagecontrol/src/get_folder.php
- storagecontrol/src/list_folders.php
- storagecontrol/src/rename_folder.php
- storagecontrol/test/StorageControlTest.php
Fixes https://github.com/googleapis/google-cloud-php/issues/7357
```
➜  storagecontrol git:(main) ✗ ../testing/vendor/bin/phpunit -c phpunit.xml.dist --testdox
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.
Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
Storage Control (Google\Cloud\Samples\StorageControl\StorageControl)
✔ Create folder
✔ Get folder
✔ List folders
✔ Rename folder
✔ Delete folder
quickstart
✔ Quickstart
Time: 00:10.662, Memory: 12.00 MB
OK (6 tests, 7 assertions)
➜  storagecontrol git:(main) ✗
```
> feat(storagecontrol): add HNS folders samples

- storagecontrol/src/managed_folder_create.php
- storagecontrol/src/managed_folder_delete.php
- storagecontrol/src/managed_folder_get.php
- storagecontrol/src/managed_folders_list.php
- storagecontrol/test/StorageControlTest.php
Fixes https://github.com/googleapis/google-cloud-php/issues/7376
> feat(storagecontrol): add samples for managed folders

- appengine/flexible/datastore/app.yaml
- appengine/flexible/helloworld/app.yaml
- appengine/flexible/storage/app.yaml
Update the PHP versions to use 8.3 for some of the doc samples.
> chore: Update some PHP GAE Flex samples to use newer runtimes

- datastore/api/src/query_filter_compound_multi_ineq.php
- datastore/api/test/ConceptsTest.php
- adds new sample `query_filter_compound_multi_ineq `
- removes now invalid sample `inequality_invalid` (see #2033)
> feat(Datastore): add samples for  multiple inequality

- CODEOWNERS
Replace outdated cloud-storage-dpe group
> chore: set gcs-sdk-team as CODEOWNERS

- documentai/composer.json
- documentai/phpunit.xml.dist
- documentai/quickstart.php
Fixes Internal: b/393632125
- Update `google/cloud-document-ai` to the latest version `2.1.3`
- Refactor sample to comply with new syntax requested by the client library
- Migrate phpunit XML definition to v9.3, as requested when running the test
> fix(documentai): fix 'quickstart' for latest client-library

- translate/src/v3_translate_text.php
> chore(translate): add region tag 'v3_import_client_library'

- pubsub/api/src/subscriber_error_listener.php
- pubsub/api/test/pubsubTest.php
https://buganizer.corp.google.com/issues/416330649
> feat(PubSub): Add SubscriberErrorListener sample

- pubsub/api/src/update_topic_type.php
- pubsub/api/test/pubsubTest.php
> feat(PubSub): Add update_topic_type sample

- pubsub/api/README.md
- pubsub/api/test/pubsubTest.php
These variables are needed for testing multiple new samples.
> docs(PubSub): README improvements

- pubsub/api/src/create_topic_with_aws_msk_ingestion.php
- pubsub/api/test/pubsubTest.php
https://b.corp.google.com/issues/390688017
> feat(PubSub): Add CreateTopicWithAwsMskIngestion sample

- pubsub/api/src/create_topic_with_azure_event_hubs_ingestion.php
- pubsub/api/test/pubsubTest.php
https://buganizer.corp.google.com/issues/390688018
> feat(PubSub): Add create_topic_with_azure_event_hubs_ingestion sample

- storage/src/disable_soft_delete.php
- storage/src/get_soft_delete_policy.php
- storage/src/list_soft_deleted_object_versions.php
- storage/src/list_soft_deleted_objects.php
- storage/src/restore_soft_deleted_object.php
- storage/src/set_soft_delete_policy.php
- storage/test/ObjectsTest.php
- storage/test/storageTest.php
> feat(storage): add samples for soft delete (objects)

- secretmanager/composer.json
- secretmanager/src/bind_tags_to_regional_secret.php
- secretmanager/src/bind_tags_to_secret.php
- secretmanager/src/create_regional_secret_with_tags.php
- secretmanager/src/create_secret_with_tags.php
- secretmanager/test/regionalsecretmanagerTest.php
- secretmanager/test/secretmanagerTest.php
Created samples for Global and Regional Secret Manager API
1. Create Secret With Tags
2. Bind Tags to Secret
Ref: https://cloud.google.com/secret-manager/docs/create-and-manage-tags 
Please merge this PR for me once it is approved
> feat(secretmanager): Added samples for tags field

- storage/composer.json
- storage/src/configure_retries.php
Example on how to pass configuration related to retries to `StorageClient` and operations that include:
- retries
- retry strategy 
- delay function
- calc delay function
- retry function
Fixes googleapis/google-cloud-php#8309.
> feat(Storage): adding retry configuration example.
